// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Globalization;
using System.Text;

namespace Vixen.Samples.Mmo.Authoring;

/// <summary>Writes one definition file.</summary>
/// <remarks>
///     <para>
///         ⚠ <b>A YAML writer rather than a serialiser, and the reason is the header.</b> Every file
///         this emits carries a line saying it was generated and which table row produced it, so
///         somebody who opens one knows not to edit it. A serialiser would round-trip the object and
///         drop the comment, which is the whole of what makes the output readable.
///     </para>
///     <para>
///         ⚠ <b>Floats are written invariant and trimmed.</b> A generator that emitted <c>1,5</c> on
///         a machine with a comma decimal separator would produce content that parses to something
///         else, and the failure would only appear on that machine.
///     </para>
/// </remarks>
sealed class Yaml(string tag, string note) {
    readonly StringBuilder text = new();
    int indent;

    /// <summary>Writes a scalar field.</summary>
    /// <param name="name">Its name, camel-cased.</param>
    /// <param name="value">Its value.</param>
    /// <returns>This, so calls chain.</returns>
    public Yaml Put(string name, string? value) {
        if (!string.IsNullOrEmpty(value)) {
            Line($"{name}: {Quote(value)}");
        }

        return this;
    }

    /// <summary>Writes a number, unless it is the default nobody needs to see.</summary>
    /// <param name="name">Its name.</param>
    /// <param name="value">Its value.</param>
    /// <param name="skip">A value to omit, so a file is not full of zeroes.</param>
    /// <returns>This.</returns>
    public Yaml Put(string name, int value, int? skip = null) {
        if (value != skip) {
            Line($"{name}: {value.ToString(CultureInfo.InvariantCulture)}");
        }

        return this;
    }

    /// <summary>Writes a number.</summary>
    /// <param name="name">Its name.</param>
    /// <param name="value">Its value.</param>
    /// <param name="skip">A value to omit.</param>
    /// <returns>This.</returns>
    public Yaml Put(string name, float value, float? skip = null) {
        if (value != skip) {
            Line($"{name}: {Number(value)}");
        }

        return this;
    }

    /// <summary>Writes a boolean, only when it is true.</summary>
    /// <param name="name">Its name.</param>
    /// <param name="value">Its value.</param>
    /// <returns>This.</returns>
    public Yaml Put(string name, bool value) {
        if (value) {
            Line($"{name}: true");
        }

        return this;
    }

    /// <summary>Writes a flow sequence of scalars, unless it is empty.</summary>
    /// <param name="name">Its name.</param>
    /// <param name="values">Its values.</param>
    /// <returns>This.</returns>
    public Yaml List(string name, IEnumerable<string> values) {
        var items = values.ToArray();

        if (items.Length > 0) {
            Line($"{name}: [ {string.Join(", ", items.Select(Quote))} ]");
        }

        return this;
    }

    /// <summary>Opens a nested mapping.</summary>
    /// <param name="name">Its name.</param>
    /// <returns>This.</returns>
    public Yaml Open(string name) {
        Line($"{name}:");
        indent++;

        return this;
    }

    /// <summary>Opens an item of a sequence of mappings.</summary>
    /// <param name="name">The sequence's name, or null to continue one already open.</param>
    /// <returns>This.</returns>
    public Yaml Item(string? name = null) {
        if (name is not null) {
            Line($"{name}:");
        }

        text.Append(new string(' ', indent * 2)).Append("- ");
        indent++;
        pending = true;

        return this;
    }

    /// <summary>Closes a nesting level.</summary>
    /// <returns>This.</returns>
    public Yaml Close() {
        // ⚠ A generator bug, not a content one, and worth saying so: an unbalanced Open/Item/Close
        // produces a negative indent, and `new string(' ', -2)` throws somewhere with no useful
        // stack. Saying which tag was being written turns a five-minute hunt into a glance.
        if (--indent < 0) {
            throw new InvalidOperationException($"Closed one level too many while writing !{tag}.");
        }

        return this;
    }

    /// <summary>Writes a comment line, for the handful of rows that need one.</summary>
    /// <param name="comment">What it says.</param>
    /// <returns>This.</returns>
    public Yaml Note(string comment) {
        Line($"# {comment}");

        return this;
    }

    /// <inheritdoc />
    public override string ToString() =>
        "# Generated by Mmo.Content.Authoring. " + note + Environment.NewLine
        + "# Edit the table it came from, not this file." + Environment.NewLine
        + "!" + tag + Environment.NewLine
        + text;

    static string Number(float value) =>
        value == MathF.Round(value)
            ? ((int)value).ToString(CultureInfo.InvariantCulture)
            : value.ToString("0.####", CultureInfo.InvariantCulture);

    // Quoted only when it would otherwise parse as something else. An address never needs it; a
    // display name with a colon in it does.
    static string Quote(string value) =>
        value.Contains(':', StringComparison.Ordinal) || value.Contains('#', StringComparison.Ordinal)
            ? $"\"{value.Replace("\"", "\\\"", StringComparison.Ordinal)}\""
            : value;

    bool pending;

    void Line(string line) {
        if (pending) {
            pending = false;
        } else {
            text.Append(new string(' ', indent * 2));
        }

        text.AppendLine(line);
    }
}
