// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Text;

namespace Vixen.Input.Generators;

/// <summary>Writes the C# accessor class for one <c>.vxinput</c>.</summary>
/// <remarks>
///     <para>
///         Strings rather than a syntax tree. The output is one shape with three loops in it, and a
///         <c>SyntaxFactory</c> version would be four times the length and no more correct — the
///         property that matters is that every name is put through <see cref="Sanitise" /> before it
///         reaches the buffer, which a tree does not check either.
///     </para>
///     <para>
///         Everything is emitted fully qualified with <c>global::</c>. A generated file lands in the
///         consumer's namespace, and a game with its own <c>InputAction</c> class would otherwise
///         get an error inside code it did not write and cannot edit.
///     </para>
/// </remarks>
internal static class VxInputEmitter {
    /// <summary>Emits the accessor class.</summary>
    /// <param name="asset">The document, already read.</param>
    /// <param name="namespaceName">Where the class goes, or empty for the global namespace.</param>
    /// <param name="source">The document's text, embedded so that <c>Create()</c> needs no file.</param>
    /// <returns>The C#.</returns>
    public static string Emit(InputActionAssetData asset, string namespaceName, string source) {
        var className = Sanitise(asset.Name, "InputActions");
        var builder = new StringBuilder(4096);

        builder.Append("// <auto-generated/>\n")
            .Append("// Generated from a .vxinput by Vixen.Input.Generators. Do not edit.\n")
            .Append("#nullable enable\n\n");

        if (namespaceName.Length > 0) {
            builder.Append("namespace ").Append(namespaceName).Append(";\n\n");
        }

        var reserved = new HashSet<string>(StringComparer.Ordinal) {
            className,
            "Actions",
            "Source",
            "Create",
            "Enable",
            "Disable",
            "Equals",
            "GetHashCode",
            "GetType",
            "ToString"
        };

        var maps = new List<MapNames>();

        foreach (var map in asset.Maps) {
            var property = Unique(reserved, Sanitise(map.Name, "Map"));
            maps.Add(new(map, property, property + "Actions"));
        }

        builder.Append("/// <summary>The actions of <c>").Append(Escape(asset.Name)).Append("</c>.</summary>\n")
            .Append("/// <remarks>Generated from a <c>.vxinput</c>. Renaming an action in the asset breaks every\n")
            .Append("/// use site at compile time, which is the whole point of it.</remarks>\n")
            .Append("public sealed partial class ").Append(className).Append(" {\n");

        builder.Append("    /// <summary>The document this class was generated from.</summary>\n")
            .Append("    public const string Source = \"").Append(Literal(source)).Append("\";\n\n");

        builder.Append("    /// <summary>Wraps an asset that has already been loaded.</summary>\n")
            .Append("    /// <param name=\"actions\">The asset.</param>\n")
            .Append("    public ").Append(className).Append("(global::Vixen.Input.InputActions actions) {\n")
            .Append("        Actions = actions;\n");

        foreach (var map in maps) {
            builder.Append("        ").Append(map.Property).Append(" = new ").Append(map.TypeName)
                .Append("(actions[\"").Append(Escape(map.Data.Name)).Append("\"]);\n");
        }

        builder.Append("    }\n\n");

        builder.Append("    /// <summary>Loads the embedded document into a fresh asset.</summary>\n")
            .Append("    /// <returns>The actions.</returns>\n")
            .Append("    /// <remarks>Needs no file and no content pipeline, which is what makes this work in a\n")
            .Append("    /// unit test and in a trimmed player alike.</remarks>\n")
            .Append("    public static ").Append(className).Append(" Create() =>\n")
            .Append("        new(global::Vixen.Input.InputActions.Load(Source, \"")
            .Append(Escape(asset.Name)).Append("\"));\n\n");

        builder.Append("    /// <summary>The asset underneath.</summary>\n")
            .Append("    public global::Vixen.Input.InputActions Actions { get; }\n\n");

        foreach (var map in maps) {
            builder.Append("    /// <summary>The <c>").Append(Escape(map.Data.Name))
                .Append("</c> action map.</summary>\n")
                .Append("    public ").Append(map.TypeName).Append(' ').Append(map.Property).Append(" { get; }\n\n");
        }

        builder.Append("    /// <summary>Enables every map.</summary>\n")
            .Append("    public void Enable() => Actions.Enable();\n\n")
            .Append("    /// <summary>Disables every map.</summary>\n")
            .Append("    public void Disable() => Actions.Disable();\n");

        foreach (var map in maps) {
            EmitMap(builder, map);
        }

        return builder.Append("}\n").ToString();
    }

    static void EmitMap(StringBuilder builder, MapNames map) {
        var reserved = new HashSet<string>(StringComparer.Ordinal) {
            map.TypeName,
            "Map",
            "Enable",
            "Disable",
            "Equals",
            "GetHashCode",
            "GetType",
            "ToString"
        };

        var actions = new List<(InputActionData Data, string Property)>();

        foreach (var action in map.Data.Actions) {
            actions.Add((action, Unique(reserved, Sanitise(action.Name, "Action"))));
        }

        builder.Append("\n    /// <summary>The actions of the <c>").Append(Escape(map.Data.Name))
            .Append("</c> map.</summary>\n")
            .Append("    public sealed partial class ").Append(map.TypeName).Append(" {\n")
            .Append("        /// <summary>Wraps a map that has already been loaded.</summary>\n")
            .Append("        /// <param name=\"map\">The map.</param>\n")
            .Append("        public ").Append(map.TypeName).Append("(global::Vixen.Input.InputActionMap map) {\n")
            .Append("            Map = map;\n");

        foreach (var (data, property) in actions) {
            builder.Append("            ").Append(property).Append(" = map[\"").Append(Escape(data.Name))
                .Append("\"];\n");
        }

        builder.Append("        }\n\n")
            .Append("        /// <summary>The map underneath.</summary>\n")
            .Append("        public global::Vixen.Input.InputActionMap Map { get; }\n");

        foreach (var (data, property) in actions) {
            builder.Append("\n        /// <summary>The <c>").Append(Escape(data.Name))
                .Append("</c> action — ").Append(Describe(data)).Append(".</summary>\n")
                .Append("        public global::Vixen.Input.InputAction ").Append(property).Append(" { get; }\n");
        }

        builder.Append("\n        /// <summary>Starts listening.</summary>\n")
            .Append("        public void Enable() => Map.Enable();\n\n")
            .Append("        /// <summary>Stops listening.</summary>\n")
            .Append("        public void Disable() => Map.Disable();\n")
            .Append("    }\n");
    }

    /// <summary>What to say about an action in the one line a tooltip shows.</summary>
    static string Describe(InputActionData action) {
        var shape = action.ControlType switch {
            InputControlType.Vector2 => "read it with <c>ReadValue&lt;Vector2&gt;()</c>",
            InputControlType.Axis => "read it with <c>ReadValue&lt;float&gt;()</c>",
            _ => "read it with <c>IsPressed</c> or <c>WasPressedThisFrame</c>"
        };

        var type = action.Type switch {
            InputActionType.Value => "a value action",
            InputActionType.PassThrough => "a pass-through action",
            _ => "a button action"
        };

        return type + ", " + shape;
    }

    /// <summary>Turns an authored name into something that can be a C# identifier.</summary>
    /// <remarks>
    ///     An action map may legitimately be called <c>UI / HUD</c>, and neither the author nor the
    ///     asset should have to care that C# cannot spell that. What is <em>not</em> silently fixed is
    ///     a collision, which <see cref="Unique" /> handles by suffixing rather than by dropping one
    ///     of the two members.
    /// </remarks>
    static string Sanitise(string name, string fallback) {
        var builder = new StringBuilder(name.Length + 1);

        foreach (var character in name) {
            if (char.IsLetterOrDigit(character) || character == '_') {
                builder.Append(character);
            }
        }

        if (builder.Length == 0) {
            return fallback;
        }

        if (char.IsDigit(builder[0])) {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    static string Unique(HashSet<string> taken, string name) {
        var candidate = name;
        var suffix = 2;

        while (!taken.Add(candidate)) {
            candidate = name + suffix.ToString(System.Globalization.CultureInfo.InvariantCulture);
            suffix++;
        }

        return candidate;
    }

    /// <summary>Escapes text for an XML documentation comment.</summary>
    static string Escape(string text) {
        var builder = new StringBuilder(text.Length);

        foreach (var character in text) {
            switch (character) {
                case '<': builder.Append("&lt;"); break;
                case '>': builder.Append("&gt;"); break;
                case '&': builder.Append("&amp;"); break;
                case '\r': break;
                case '\n': builder.Append(' '); break;
                default: builder.Append(character); break;
            }
        }

        return builder.ToString();
    }

    /// <summary>Escapes text for a C# string literal.</summary>
    /// <remarks>
    ///     A quoted literal with escapes rather than a raw string literal: the document is arbitrary
    ///     text and a raw literal's fence has to be longer than any run of quotes inside it, which is
    ///     a rule with an off-by-one that produces uncompilable generated code on somebody's asset
    ///     rather than on any of ours.
    /// </remarks>
    static string Literal(string text) {
        var builder = new StringBuilder(text.Length + 32);

        foreach (var character in text) {
            switch (character) {
                case '"': builder.Append("\\\""); break;
                case '\\': builder.Append("\\\\"); break;
                case '\n': builder.Append("\\n"); break;
                case '\r': builder.Append("\\r"); break;
                case '\t': builder.Append("\\t"); break;
                case '\0': builder.Append("\\0"); break;
                default: builder.Append(character); break;
            }
        }

        return builder.ToString();
    }

    readonly record struct MapNames(InputActionMapData Data, string Property, string TypeName);
}
