// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Vixen.Ecs.Generators;

/// <summary>
///     Emits the query surface for one to sixteen component types: the description builders, the
///     delegates, the struct-visitor interfaces and the iteration that drives them.
/// </summary>
/// <remarks>
///     <para>
///         What [04](../../docs/plan/04-ecs-and-scripting.md) § Queries asks for, and what Arch
///         produces with T4 templates. Sixteen arities across four families is roughly two thousand
///         lines of code whose only variable is a number; writing that by hand means sixteen chances
///         to transpose an index in a place where the compiler cannot help, because every arity
///         type-checks whether or not the body is right.
///     </para>
///     <para>
///         Emitted at post-initialisation, because the output does not depend on anything in the
///         compilation. It is registered only by <c>Vixen.Ecs</c> itself and does not travel in the
///         package: an assembly that referenced it would emit a second copy of the same partial and
///         the same extension class. The generators that <i>do</i> belong in a user's compilation —
///         system read/write inference, the behaviour dispatch table — join this project with the
///         layers that need them.
///     </para>
///     <para>
///         The generated loops walk with <c>Unsafe.Add</c> over the first element rather than
///         indexing the spans. A span's bounds check is elided when the loop bound is its own
///         <c>Length</c>, and here the bound is the chunk's count, shared by every column — so
///         indexing would pay for <i>n</i> bounds checks per entity that no arrangement of the loop
///         can remove.
///     </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class QueryArityGenerator : IIncrementalGenerator {
    const int MaxArity = 16;

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(output => {
                output.AddSource("QueryDescription.Arities.g.cs", SourceText.From(Descriptions(), Encoding.UTF8));
                output.AddSource("QueryDelegates.g.cs", SourceText.From(Delegates(), Encoding.UTF8));
                output.AddSource("QueryVisitors.g.cs", SourceText.From(Visitors(), Encoding.UTF8));
                output.AddSource("WorldQueryExtensions.g.cs", SourceText.From(Iteration(), Encoding.UTF8));
            }
        );

    static string Header() =>
        """
        // <auto-generated/>
        // SPDX-FileCopyrightText: Copyright (c) Rikarin
        // SPDX-License-Identifier: Apache-2.0
        //
        // Generated by Vixen.Ecs.Generators.QueryArityGenerator. Do not edit.

        #nullable enable


        """;

    static string Parameters(int arity) => string.Join(", ", Range(arity).Select(index => $"T{index}"));

    static string TypeArguments(int arity) => $"<{Parameters(arity)}>";

    static IEnumerable<int> Range(int arity) => Enumerable.Range(0, arity);

    static string TypeParameterDocumentation(int arity, string indent) =>
        string.Join(
            "\n",
            Range(arity).Select(index =>
                $"{indent}/// <typeparam name=\"T{index}\">Component type {index}.</typeparam>"
            )
        );

    // ---------------------------------------------------------------- description builders

    static string Descriptions() {
        var text = new StringBuilder(Header());

        text.AppendLine("using Vixen.Core;");
        text.AppendLine();
        text.AppendLine("namespace Vixen.Ecs;");
        text.AppendLine();
        text.AppendLine("public sealed partial class QueryDescription {");

        foreach (var arity in Enumerable.Range(1, MaxArity)) {
            Builder(text, arity, "WithAll", "RequireAll", "Requires every one of these components.");
            Builder(
                text,
                arity,
                "WithAny",
                "RequireAny",
                "Requires at least one of these components."
            );

            Builder(text, arity, "WithNone", "Exclude", "Excludes entities that have any of these components.");
            Builder(
                text,
                arity,
                "WithChanged",
                "RequireChanged",
                "Requires these components, and narrows iteration to chunks in which one of them changed."
            );
        }

        text.AppendLine("}");
        return text.ToString();
    }

    static void Builder(StringBuilder text, int arity, string name, string target, string summary) {
        text.AppendLine($"    /// <summary>{summary}</summary>");
        text.AppendLine(TypeParameterDocumentation(arity, "    "));
        text.AppendLine("    /// <returns>This description, for chaining.</returns>");
        text.AppendLine($"    public QueryDescription {name}{TypeArguments(arity)}() =>");
        text.AppendLine($"        {target}([{string.Join(", ", Range(arity).Select(index => $"ComponentType<T{index}>.Id"))}]);");
        text.AppendLine();
    }

    // ---------------------------------------------------------------- delegates

    static string Delegates() {
        var text = new StringBuilder(Header());

        text.AppendLine("using Vixen.Core;");
        text.AppendLine();
        text.AppendLine("namespace Vixen.Ecs;");
        text.AppendLine();

        foreach (var arity in Enumerable.Range(1, MaxArity)) {
            var refParameters = string.Join(", ", Range(arity).Select(index => $"ref T{index} component{index}"));

            text.AppendLine("/// <summary>What a query does to each entity's components.</summary>");
            text.AppendLine(TypeParameterDocumentation(arity, ""));

            foreach (var index in Range(arity)) {
                text.AppendLine($"/// <param name=\"component{index}\">A reference into the chunk.</param>");
            }

            text.AppendLine($"public delegate void QueryAction{TypeArguments(arity)}({refParameters});");
            text.AppendLine();

            text.AppendLine("/// <summary>What a query does to each entity and its components.</summary>");
            text.AppendLine(TypeParameterDocumentation(arity, ""));
            text.AppendLine("/// <param name=\"entity\">The entity the components belong to.</param>");

            foreach (var index in Range(arity)) {
                text.AppendLine($"/// <param name=\"component{index}\">A reference into the chunk.</param>");
            }

            text.AppendLine(
                $"public delegate void QueryEntityAction{TypeArguments(arity)}(Entity entity, {refParameters});"
            );

            text.AppendLine();
        }

        return text.ToString();
    }

    // ---------------------------------------------------------------- visitors

    static string Visitors() {
        var text = new StringBuilder(Header());

        text.AppendLine("using Vixen.Core;");
        text.AppendLine();
        text.AppendLine("namespace Vixen.Ecs;");
        text.AppendLine();

        foreach (var arity in Enumerable.Range(1, MaxArity)) {
            var refParameters = string.Join(", ", Range(arity).Select(index => $"ref T{index} component{index}"));

            text.AppendLine("/// <summary>A struct visitor a query calls per entity, with no delegate to dispatch through.</summary>");
            text.AppendLine(TypeParameterDocumentation(arity, ""));
            text.AppendLine("/// <remarks>");
            text.AppendLine("///     Constrained to <c>struct</c> where it is used, so the call is monomorphic and the JIT");
            text.AppendLine("///     inlines the body into the loop. This is the form to reach for when the delegate's");
            text.AppendLine("///     indirect call shows up in a profile.");
            text.AppendLine("/// </remarks>");
            text.AppendLine($"public interface IForEach{TypeArguments(arity)} {{");
            text.AppendLine("    /// <summary>Runs on one entity's components.</summary>");

            foreach (var index in Range(arity)) {
                text.AppendLine($"    /// <param name=\"component{index}\">A reference into the chunk.</param>");
            }

            text.AppendLine($"    void Execute({refParameters});");
            text.AppendLine("}");
            text.AppendLine();

            text.AppendLine("/// <summary>A struct visitor a query calls per entity, with the entity handle.</summary>");
            text.AppendLine(TypeParameterDocumentation(arity, ""));
            text.AppendLine($"public interface IForEachWithEntity{TypeArguments(arity)} {{");
            text.AppendLine("    /// <summary>Runs on one entity and its components.</summary>");
            text.AppendLine("    /// <param name=\"entity\">The entity the components belong to.</param>");

            foreach (var index in Range(arity)) {
                text.AppendLine($"    /// <param name=\"component{index}\">A reference into the chunk.</param>");
            }

            text.AppendLine($"    void Execute(Entity entity, {refParameters});");
            text.AppendLine("}");
            text.AppendLine();
        }

        return text.ToString();
    }

    // ---------------------------------------------------------------- iteration

    static string Iteration() {
        var text = new StringBuilder(Header());

        text.AppendLine("using System.Runtime.InteropServices;");
        text.AppendLine("using System.Runtime.CompilerServices;");
        text.AppendLine("using Vixen.Core;");
        text.AppendLine();
        text.AppendLine("namespace Vixen.Ecs;");
        text.AppendLine();
        text.AppendLine("/// <summary>Runs a body over every entity a query matches.</summary>");
        text.AppendLine("public static class WorldQueryExtensions {");

        foreach (var arity in Enumerable.Range(1, MaxArity)) {
            Loop(text, arity, withEntity: false, visitor: false);
            Loop(text, arity, withEntity: true, visitor: false);
            Loop(text, arity, withEntity: false, visitor: true);
            Loop(text, arity, withEntity: true, visitor: true);
        }

        text.AppendLine("}");
        return text.ToString();
    }

    static void Loop(StringBuilder text, int arity, bool withEntity, bool visitor) {
        var suffix = withEntity ? "WithEntity" : "";
        var name = visitor ? $"ForEach{suffix}" : $"Query{suffix}";
        var interfaceName = withEntity ? "IForEachWithEntity" : "IForEach";
        var delegateName = withEntity ? "QueryEntityAction" : "QueryAction";

        var typeArguments = visitor
            ? $"<TVisitor, {Parameters(arity)}>"
            : TypeArguments(arity);

        var body = visitor
            ? "ref TVisitor visitor"
            : $"{delegateName}{TypeArguments(arity)} action";

        text.AppendLine("    /// <summary>Runs the body over every entity the query matches.</summary>");

        if (visitor) {
            text.AppendLine("    /// <typeparam name=\"TVisitor\">The visitor's type, so the call is not virtual.</typeparam>");
        }

        text.AppendLine(TypeParameterDocumentation(arity, "    "));
        text.AppendLine("    /// <param name=\"world\">The world to iterate.</param>");
        text.AppendLine("    /// <param name=\"description\">Which entities.</param>");
        text.AppendLine(
            visitor
                ? "    /// <param name=\"visitor\">The body. Passed by reference, so it can accumulate.</param>"
                : "    /// <param name=\"action\">The body.</param>"
        );

        text.AppendLine("    /// <param name=\"since\">Only chunks written after this version, when the description filters on change.</param>");
        text.AppendLine($"    public static void {name}{typeArguments}(");
        text.AppendLine("        this World world,");
        text.AppendLine("        QueryDescription description,");
        text.AppendLine($"        {body},");
        text.AppendLine("        uint since = 0");
        text.AppendLine("    )");

        if (visitor) {
            text.AppendLine($"        where TVisitor : struct, {interfaceName}{TypeArguments(arity)}");
        }

        text.AppendLine("    {");
        text.AppendLine("        ArgumentNullException.ThrowIfNull(world);");

        if (!visitor) {
            text.AppendLine("        ArgumentNullException.ThrowIfNull(action);");
        }

        text.AppendLine();
        text.AppendLine("        foreach (var chunk in world.Chunks(description, since)) {");
        text.AppendLine("            var count = chunk.Count;");

        if (withEntity) {
            text.AppendLine("            ref var entities = ref MemoryMarshal.GetReference(chunk.Entities);");
        }

        foreach (var index in Range(arity)) {
            text.AppendLine(
                $"            ref var component{index} = ref MemoryMarshal.GetReference(chunk.Values<T{index}>());"
            );
        }

        text.AppendLine();
        text.AppendLine("            for (var index = 0; index < count; index++) {");

        var arguments = string.Join(
            ", ",
            Range(arity).Select(index => $"ref Unsafe.Add(ref component{index}, index)")
        );

        if (withEntity) {
            arguments = $"Unsafe.Add(ref entities, index), {arguments}";
        }

        text.AppendLine(visitor
            ? $"                visitor.Execute({arguments});"
            : $"                action({arguments});"
        );

        text.AppendLine("            }");
        text.AppendLine("        }");
        text.AppendLine("    }");
        text.AppendLine();
    }
}
