// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using Vixen.YogaTestGen;

var yoga = args.Length > 0 ? args[0] : Path.Combine("references", "yoga");
var output = args.Length > 1 ? args[1] : Path.Combine("Core", "Vixen.Ui.Layout.Tests", "Generated");

var fixtures = Path.Combine(yoga, "tests", "generated");
if (!Directory.Exists(fixtures)) {
    Console.Error.WriteLine(
        $"No fixtures at '{fixtures}'. Clone the reference — references/README.md has the command — "
        + "or pass the path to a Yoga checkout as the first argument."
    );

    return 1;
}

Directory.CreateDirectory(output);
foreach (var stale in Directory.GetFiles(output, "*.g.cs")) {
    File.Delete(stale);
}

var totalTests = 0;
var totalSkipped = new List<(string File, SkippedTest Test)>();

foreach (var path in Directory.GetFiles(fixtures, "*.cpp").OrderBy(path => path, StringComparer.Ordinal)) {
    var fixture = Path.GetFileNameWithoutExtension(path);
    var skipped = new List<SkippedTest>();
    var tests = CppTranslator.Translate(File.ReadAllText(path), skipped);

    totalSkipped.AddRange(skipped.Select(test => (fixture, test)));
    if (tests.Count == 0) {
        continue;
    }

    totalTests += tests.Count;
    File.WriteAllText(Path.Combine(output, ClassName(fixture) + ".g.cs"), Emit(fixture, tests, skipped));
}

Console.WriteLine($"{totalTests} conformance tests written to {output}.");
if (totalSkipped.Count > 0) {
    Console.WriteLine($"{totalSkipped.Count} fixtures skipped:");
    foreach (var (file, test) in totalSkipped) {
        Console.WriteLine($"  {file}.{test.Test}: {test.Reason}");
    }
}

return 0;

static string ClassName(string fixture) {
    var name = fixture.StartsWith("YG", StringComparison.Ordinal) ? fixture[2..] : fixture;
    return name.EndsWith("Test", StringComparison.Ordinal) ? name + "s" : name + "Tests";
}

static string Emit(string fixture, List<TranslatedTest> tests, List<SkippedTest> skipped) {
    var text = new StringBuilder();
    text.AppendLine("// SPDX-FileCopyrightText: Copyright (c) Rikarin");
    text.AppendLine("// SPDX-License-Identifier: Apache-2.0");
    text.AppendLine("//");
    text.AppendLine("// <auto-generated>");
    text.AppendLine($"//     Translated by Tools/Vixen.YogaTestGen from Yoga's {fixture}.cpp, which Yoga in turn");
    text.AppendLine("//     generates from an HTML fixture laid out by a real browser. Every number below is");
    text.AppendLine("//     Chrome's answer, which is what makes this a conformance suite rather than a");
    text.AppendLine("//     regression suite. Do not edit: re-run the tool.");

    if (skipped.Count > 0) {
        text.AppendLine("//");
        text.AppendLine($"//     {skipped.Count} fixture(s) in this file were NOT translated:");
        foreach (var test in skipped) {
            text.AppendLine($"//       {test.Test} — no equivalent for: {test.Reason}");
        }
    }

    text.AppendLine("// </auto-generated>");
    text.AppendLine();
    text.AppendLine("using Xunit;");
    text.AppendLine();
    text.AppendLine("namespace Vixen.Ui.Layout.Tests.Generated;");
    text.AppendLine();
    text.AppendLine("public class " + ClassName(fixture) + " {");
    text.AppendLine("    const float Tolerance = 0.0001f;");

    foreach (var test in tests) {
        text.AppendLine();
        text.AppendLine("    [Fact]");
        text.AppendLine($"    public void {char.ToUpperInvariant(test.Name[0]) + test.Name[1..]}() {{");
        text.AppendLine("        using var tree = new LayoutTree();");
        text.AppendLine();

        foreach (var statement in test.Body) {
            text.AppendLine(statement.Length == 0 ? string.Empty : "        " + statement);
        }

        text.AppendLine("    }");
    }

    text.AppendLine("}");
    return text.ToString().ReplaceLineEndings("\n");
}
