// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using Xunit;

namespace Vixen.Ui.Layout.Tests;

/// <summary>
///     doc 43 § T5 — a transcribed conformance fixture owes a <c>NOTICE</c> entry, and this is what
///     notices that it does not have one.
/// </summary>
/// <remarks>
///     <para>
///         <b>The obligation attaches to the expected values, not to a copied file.</b> § T5 says a
///         <c>NOTICE</c> entry for <c>web-platform-tests</c> is required "the moment a translated
///         fixture lands", because BSD-3-Clause asks for the copyright notice and the disclaimer to
///         travel with a redistribution of the material in any form — and thirty accepted values with
///         the serialisation the suite asserts for each, quoted case for case into a
///         <c>[Theory]</c>, is that material. Nothing is copied, and the obligation is the same.
///     </para>
///     <para>
///         ⚠ <b>Which is exactly the shape that goes unnoticed.</b> The Yoga and Taffy corpora are
///         generated by a tool, so their <c>NOTICE</c> entries were written by whoever wrote the
///         tool. A hand-transcribed theory arrives as an ordinary test file in an ordinary pull
///         request, and <c>Pack</c> — the one gate that reads a <c>NOTICE</c> at all — only checks
///         that each package <i>carries</i> one, never what it says. Four files cited
///         <c>web-platform-tests</c> before this test existed and the <c>NOTICE</c> named none of
///         them.
///     </para>
///     <para>
///         <b>What it prints on the day it does not run.</b> A sweep that finds nothing passes, and a
///         passing licence gate that has stopped sweeping is worse than none — so
///         <see cref="Every_declared_corpus_is_actually_cited" /> asserts the sweep still has bite
///         before <see cref="A_cited_corpus_is_recorded_in_the_notice" /> asserts anything about the
///         <c>NOTICE</c>. If a citation is renamed the first test goes red rather than the second
///         going quietly green.
///     </para>
///     <para>
///         ⚠ <b><c>.claude</c> is pruned, and that is not housekeeping.</b> Agent worktrees under
///         <c>.claude/worktrees/</c> are full checkouts, so a sweep that walks them asserts against
///         other people's uncommitted work — a true statement about a tree nobody was asking about.
///         <c>TypeSelectorReachTests</c> failed a gate run that way and this list is its list.
///     </para>
///     <para>
///         <b>The sweep reads <c>.cs</c> under a <c>*.Tests</c> directory, and no more.</b> A
///         transcribed expected value lives in a test; an implementation file that merely names the
///         suite it was written against — <c>GridAreaTemplate.cs</c> does — redistributes nothing and
///         is deliberately out of scope. A corpus committed as *data* rather than as C# would slip
///         past this, and the two that exist (Yoga, Taffy) are generated by tools that write their
///         own provenance line. That is the honest limit of this instrument.
///     </para>
/// </remarks>
public class ConformanceCorpusNoticeTests {
    /// <summary>A corpus, the token a file transcribing from it will contain, and its NOTICE heading.</summary>
    /// <param name="Citation">The spelling a transcribing file uses to name its oracle.</param>
    /// <param name="Heading">The line the NOTICE's conformance-corpora section carries for it.</param>
    /// <param name="Licence">The licence the entry has to state.</param>
    public sealed record Corpus(string Citation, string Heading, string Licence);

    /// <summary>
    ///     The corpora whose fixtures are transcribed by hand into C#, rather than generated by a
    ///     tool that writes its own provenance line.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>Adding a row here is the cheap half; the row is inert until something cites it.</b>
    ///     <see cref="Every_declared_corpus_is_actually_cited" /> is what stops a row being added
    ///     against a corpus nobody transcribes, which would read as coverage and be none.
    /// </remarks>
    public static readonly Corpus[] Corpora = [
        new("web-platform-tests", "web-platform-tests", "BSD-3-Clause"),
        new("ICU4X", "ICU4X — segmenter CSS-tailoring tests", "Unicode-3.0"),
    ];

    public static TheoryData<string> Declared {
        get {
            TheoryData<string> data = [];

            foreach (var corpus in Corpora) {
                data.Add(corpus.Citation);
            }

            return data;
        }
    }

    /// <summary>Each declared corpus is named by at least one test file, so the sweep has bite.</summary>
    [Theory]
    [MemberData(nameof(Declared))]
    public void Every_declared_corpus_is_actually_cited(string citation) {
        Assert.NotEmpty(CitingFiles(citation));
    }

    /// <summary>A cited corpus has a NOTICE entry, with its licence and its disclaimer.</summary>
    /// <remarks>
    ///     ⚠ <b>The disclaimer is asserted separately from the heading</b>, because BSD-3-Clause asks
    ///     for both and a one-line "BSD-3-Clause — &lt;url&gt;" row of the kind the reference-material
    ///     table uses satisfies neither clause. The all-caps sentence is the part that has to travel.
    /// </remarks>
    [Theory]
    [MemberData(nameof(Declared))]
    public void A_cited_corpus_is_recorded_in_the_notice(string citation) {
        var corpus = Corpora.Single(c => c.Citation == citation);
        var notice = File.ReadAllText(Path.Combine(RepositoryRoot(), "NOTICE"));
        var corpora = CorporaSection(notice);

        Assert.Contains(corpus.Heading, corpora, StringComparison.Ordinal);
        Assert.Contains(corpus.Licence, corpora, StringComparison.Ordinal);

        if (corpus.Licence.StartsWith("BSD-3", StringComparison.Ordinal)) {
            // ⚠ Unwrapped first. A NOTICE is hard-wrapped prose, so the disclaimer's sentences break
            // wherever the column ran out — the first spelling of this assertion looked for
            // "THE IMPLIED WARRANTIES OF MERCHANTABILITY" and went red on a NOTICE that carries the
            // disclaimer in full, because a newline falls after "THE".
            Assert.Contains("IMPLIED WARRANTIES OF MERCHANTABILITY", Unwrapped(corpora), StringComparison.Ordinal);
            Assert.Contains("Redistributions of source code must retain", Unwrapped(corpora), StringComparison.Ordinal);
        }
    }

    /// <summary>Every file that transcribes from a corpus is named in that corpus's NOTICE entry.</summary>
    /// <remarks>
    ///     ⚠ <b>This is the half that keeps working after today.</b> An entry naming the one file that
    ///     prompted it goes stale the first time a second fixture lands, and a stale provenance list
    ///     is the failure mode § T5 exists to prevent — the entry reads as complete and is not. The
    ///     path is asserted rather than the count, so the failure message says which file is
    ///     unrecorded.
    /// </remarks>
    [Theory]
    [MemberData(nameof(Declared))]
    public void Every_transcribing_file_is_named_in_the_entry(string citation) {
        var notice = File.ReadAllText(Path.Combine(RepositoryRoot(), "NOTICE"));
        var corpora = CorporaSection(notice);

        foreach (var file in CitingFiles(citation)) {
            Assert.Contains(file, corpora, StringComparison.Ordinal);
        }
    }

    /// <summary>The NOTICE's "incorporated as data" section, which is the one § T5 speaks about.</summary>
    /// <remarks>
    ///     ⚠ <b>Sliced rather than read whole, because the reference-material table at the bottom
    ///     already names most of these projects.</b> A test against the whole file would be satisfied
    ///     by the "read, not incorporated" row — the row that says the opposite of what the corpus
    ///     entry has to say.
    /// </remarks>
    static string CorporaSection(string notice) {
        var start = notice.IndexOf("Conformance corpora — incorporated as data", StringComparison.Ordinal);
        Assert.True(start >= 0, "the NOTICE has no conformance-corpora section.");

        var end = notice.IndexOf("Reference material — read, not incorporated", start, StringComparison.Ordinal);
        Assert.True(end > start, "the NOTICE's conformance-corpora section is not terminated.");

        return notice[start..end];
    }

    /// <summary>Every run of whitespace collapsed to one space, so a hard wrap cannot hide a sentence.</summary>
    static string Unwrapped(string text) => string.Join(' ', text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));

    /// <summary>The repository-relative paths of the test sources naming <paramref name="citation" />.</summary>
    static List<string> CitingFiles(string citation) {
        var root = RepositoryRoot();
        List<string> found = [];
        Walk(root, root, found);
        found.RemoveAll(path => !File.ReadAllText(Path.Combine(root, path)).Contains(citation, StringComparison.Ordinal));
        found.Sort(StringComparer.Ordinal);

        return found;
    }

    /// <summary>Directories a source sweep must not descend into, matched by name at any depth.</summary>
    static readonly string[] Unwalked = [".git", ".claude", "bin", "obj", "artifacts", "node_modules"];

    /// <summary>This file names every citation in <see cref="Corpora" /> and transcribes none of them.</summary>
    const string Self = "ConformanceCorpusNoticeTests.cs";

    static void Walk(string root, string directory, List<string> into) {
        if (Path.GetFileName(directory).EndsWith(".Tests", StringComparison.Ordinal)) {
            foreach (var file in Directory.EnumerateFiles(directory, "*.cs", SearchOption.AllDirectories)) {
                if (Path.GetFileName(file) != Self && !IsUnwalked(root, file)) {
                    into.Add(Path.GetRelativePath(root, file).Replace('\\', '/'));
                }
            }

            return;
        }

        foreach (var child in Directory.EnumerateDirectories(directory)) {
            if (!Unwalked.Contains(Path.GetFileName(child), StringComparer.Ordinal)) {
                Walk(root, child, into);
            }
        }
    }

    static bool IsUnwalked(string root, string file) =>
        Path.GetRelativePath(root, file)
            .Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
            .Any(segment => Unwalked.Contains(segment, StringComparer.Ordinal));

    static string RepositoryRoot() {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory);
             directory is not null;
             directory = directory.Parent) {
            if (Directory.Exists(Path.Combine(directory.FullName, "Raven", "Library"))) {
                return directory.FullName;
            }
        }

        throw new DirectoryNotFoundException($"the repository root was not found above '{AppContext.BaseDirectory}'.");
    }
}
