// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using Vixen.Core.Syntax;

namespace Vixen.Raven.Syntax;

public enum SyntaxKind : ushort {
    None,

    /// <summary>
    ///     The anonymous list node. Pinned to <see cref="SyntaxKinds.List" /> because the
    ///     shared tree creates list nodes without knowing Raven's enum; if the values
    ///     diverged, casting a list node's <c>RawKind</c> would name the wrong member.
    /// </summary>
    ListKind = SyntaxKinds.List,

    IdentifierName,
    GlobalKeyword,
    IdentifierToken,
    QualifiedName,
    DiscardPattern,
    CompilationUnit,
    PackageDirective,
    ImportDirective,
    NameColon,
    NameEquals,
    AttributeArgument,
    Attribute,
    AttributeArgumentList,
    AttributeList,
    GenericName,
    TypeArgumentList,
    PredefinedType,

    SimpleBaseType,
    ArgumentList,
    BracketedArgumentList,
    Argument,
    OutKeyword,
    InKeyword,
    EqualsValueClause,

    // ArgListKeyword
    Parameter,
    ParameterList,
    BracketedParameterList,
    AbstractKeyword,
    ComposeKeyword,
    ConstKeyword,
    OverrideKeyword,
    PartialKeyword,
    PrivateKeyword,
    ProtectedKeyword,
    PublicKeyword,
    ReadOnlyKeyword,
    StaticKeyword,
    VirtualKeyword,
    SelfExpression,
    BaseExpression,
    WhenClause,
    Block,
    BreakStatement,
    ContinueStatement,
    RepeatStatement,
    EmptyStatement,
    ExpressionStatement,
    ForStatement,
    IfStatement,
    ElseClause,
    ReturnStatement,
    LocalFunctionStatement,
    LocalDeclarationStatement,
    WhileStatement,
    SwitchStatement,
    SwitchSection,

    // CaseKeyword,
    CasePatternSwitchLabel,
    CaseSwitchLabel,
    DefaultSwitchLabel,
    VariableDeclaration,
    ConstDeclaration,
    ArrowExpressionClause,
    FieldDeclaration,
    TypeParameter,
    BaseList,
    ExpressionElement,
    SpreadElement,
    UnaryPlusExpression,
    UnaryMinusExpression,
    BitwiseNotExpression,
    LogicalNotExpression,
    PreIncrementExpression,
    PreDecrementExpression,
    IndexExpression,
    PostIncrementExpression,
    PostDecrementExpression,
    ParenthesizedExpression,
    EqualsRelationalPattern,
    NotEqualsRelationalPattern,
    LessThanRelationalPattern,
    LessThanEqualsRelationalPattern,
    GreaterThanRelationalPattern,
    GreaterThanEqualsRelationalPattern,
    TypeOfExpression,
    DefaultExpression,
    ClassConstraint,
    StructConstraint,
    QuestionToken,

    // ConstructorConstraint,
    IsPatternExpression,
    TypeConstraint,
    DefaultConstraint,
    CastExpression,
    ArrayType,
    ArrayRankSpecifier,
    TupleElement,
    TupleType,
    DiscardDesignation,

    VarPattern,
    NotPattern,
    TypePattern,
    AndPattern,
    OrPattern,
    ConstantPattern,
    ListPattern,
    SlicePattern,
    ParenthesizedPattern,
    SwitchExpression,
    SwitchExpressionArm,
    SimpleVariableDesignation,
    ParenthesizedVariableDesignation,
    TypeParameterList,

    BoolKeyword,
    Bool2Keyword,
    Bool3Keyword,
    Bool4Keyword,
    IntKeyword,
    Int2Keyword,
    Int3Keyword,
    Int4Keyword,
    UIntKeyword,
    UInt2Keyword,
    UInt3Keyword,
    UInt4Keyword,
    FloatKeyword,
    Float2Keyword,
    Float3Keyword,
    Float4Keyword,
    DoubleKeyword,
    Double2Keyword,
    Double3Keyword,
    Double4Keyword,
    Mat2Keyword,
    Mat2x3Keyword,
    Mat2x4Keyword,
    Mat3Keyword,
    Mat3x2Keyword,
    Mat3x4Keyword,
    Mat4Keyword,
    Mat4x2Keyword,
    Mat4x3Keyword,

    TypeParameterConstraintClause,

    // Tokens (full-fidelity)
    PackageKeyword,
    ImportKeyword,
    ShaderKeyword,
    StructKeyword,
    ProtocolKeyword,
    EnumKeyword,
    InitKeyword,
    GetKeyword,
    SetKeyword,
    WillSetKeyword,
    DidSetKeyword,
    FuncKeyword,
    VarKeyword,
    ValKeyword,
    TrueKeyword,
    FalseKeyword,
    DefaultKeyword,
    ReturnKeyword,
    IfKeyword,
    ElseKeyword,
    ForKeyword,
    WhileKeyword,
    NotKeyword,
    AndKeyword,
    OrKeyword,
    IsKeyword,
    SwitchKeyword,
    WhenKeyword,
    WhereKeyword,
    SelfKeyword,
    OperatorKeyword,
    ImplicitKeyword,
    ExplicitKeyword,
    UnderscoreToken,
    DotToken,
    CommaToken,
    ColonToken,
    EqualsToken,
    ArrowToken,
    DotDotToken,
    OperatorToken,
    StringLiteralToken,
    OpenParenToken,
    CloseParenToken,
    OpenBracketToken,
    CloseBracketToken,
    LessThanToken,
    GreaterThanToken,
    OpenBraceToken,
    CloseBraceToken,
    NumericLiteralToken,
    EndOfFileToken,

    ShaderDeclaration,
    StructDeclaration,
    ProtocolDeclaration,
    EnumDeclaration,
    EnumMemberDeclaration,
    ConstructorDeclaration,
    IndexerDeclaration,
    OperatorDeclaration,
    ConversionOperatorDeclaration,
    PropertyDeclaration,
    AccessorList,
    GetAccessorDeclaration,
    SetAccessorDeclaration,
    WillSetAccessorDeclaration,
    DidSetAccessorDeclaration,
    MethodDeclaration,
    InvocationExpression,
    MemberAccessExpression,
    BinaryExpression,
    AssignmentExpression,
    RangeExpression,
    TupleExpression,
    CollectionExpression,
    DeclarationExpression,
    ElementAccessExpression,
    ConditionalExpression,
    NumericLiteralExpression,
    StringLiteralExpression,
    TrueLiteralExpression,
    FalseLiteralExpression,
    DefaultLiteralExpression,

    // Trivia
    WhitespaceTrivia,
    EndOfLineTrivia,
    SingleLineCommentTrivia,
    MultiLineCommentTrivia
}

static class SyntaxKindExtensions {
    internal static SyntaxToken AsToken(this SyntaxKind kind) => SyntaxFactory.Token(kind);
}
