#version 450

// Generated by Raven from shader 'Lambert' (Vertex stage).
// Vulkan GLSL: explicit sets and bindings, separate textures and samplers.

struct Light {
    vec3 direction;
    vec3 color;
};

layout(std140, set = 2, binding = 0) uniform LambertPerMaterialUniforms {
    mat4 world;
    vec4 baseColor;
};

layout(set = 2, binding = 1) uniform texture2D albedo;
layout(set = 2, binding = 2) uniform sampler albedoSampler;

// Binding defaults are host-side data: a GLSL uniform cannot be initialized here.

layout(location = 0) in vec3 in_position;

vec4 Vertex(vec3 position) {
    mat4 _0 = world;
    vec3 _1 = position;
    vec4 _3 = vec4(_1, 1.0);
    vec4 _4 = (_0 * _3);
    return _4;
}

void main() {
    gl_Position = Vertex(in_position);
}