#version 450

// Generated by Raven from shader 'Lambert' (Pixel stage).
// Vulkan GLSL: explicit sets and bindings, separate textures and samplers.

struct Light {
    vec3 direction;
    vec3 color;
};

layout(std140, set = 2, binding = 0) uniform LambertPerMaterialUniforms {
    mat4 world;
    vec4 baseColor;
};

layout(set = 2, binding = 1) uniform texture2D albedo;
layout(set = 2, binding = 2) uniform sampler albedoSampler;

// Binding defaults are host-side data: a GLSL uniform cannot be initialized here.

layout(location = 0) in vec3 in_normal;
layout(location = 1) in vec2 in_uv;

layout(location = 0) out vec4 out_result;  // SV_Target

float Diffuse(vec3 normal, vec3 light);
vec4 Pixel(vec3 normal, vec2 uv);

float Diffuse(vec3 normal, vec3 light) {
    float ndotl;

    vec3 _0 = normal;
    vec3 _1 = normalize(_0);
    vec3 _2 = light;
    vec3 _3 = -_2;
    vec3 _4 = normalize(_3);
    float _5 = dot(_1, _4);
    ndotl = _5;
    float _6 = ndotl;
    float _8 = max(_6, 0.1);
    return _8;
}

vec4 Pixel(vec3 normal, vec2 uv) {
    float shade;
    int i;
    int i_limit;
    vec4 sampled;
    vec3 tint;

    shade = 0.0;
    i = 0;
    i_limit = 2;
    bool _loop0_first = true;
    while (true) {
        if (_loop0_first) {
            _loop0_first = false;
        } else {
            int _14 = i;
            int _16 = (_14 + 1);
            i = _16;
        }
        int _3 = i;
        int _4 = i_limit;
        bool _5 = (_3 <= _4);
        if (!(_5)) {
            break;
        }
        float _6 = shade;
        vec3 _7 = normal;
        vec3 _11 = vec3(0.0, 1.0, 0.0);
        float _12 = Diffuse(_7, _11);
        float _13 = (_6 + _12);
        shade = _13;
    }
    vec2 _19 = uv;
    vec4 _20 = texture(sampler2D(albedo, albedoSampler), _19);
    sampled = _20;
    float _21 = shade;
    bool _23 = (_21 > 1.0);
    vec3 _24 = baseColor.xyz;
    vec3 _25 = sampled.xyz;
    vec3 _26 = _23 ? _24 : _25;
    tint = _26;
    vec3 _27 = tint;
    float _28 = shade;
    vec3 _29 = vec3(_28);
    vec3 _30 = (_27 * _29);
    float _31 = sampled.w;
    vec4 _32 = vec4(_30, _31);
    return _32;
}

void main() {
    out_result = Pixel(in_normal, in_uv);
}