// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Text.RegularExpressions;
using Xunit;

namespace Vixen.Ui.Text.Tests;

/// <summary>Every artefact <c>Tools/Vixen.UnicodeTableGen</c> writes came from one UCD release.</summary>
/// <remarks>
///     <para>
///         ⚠ <b>The instrument #544 did not have.</b> <c>SpecialCasingTable.g.cs</c> said 13.0.0
///         beside nine siblings saying 17.0.0, for as long as it took somebody to <c>grep</c> the ten
///         files by eye — because the generator can regenerate that one table alone (its
///         <c>only</c> argument, which exists so the case mapping can be refreshed without the whole
///         run) and nothing in the tree read the headers. The table's <i>bytes</i> had been right the
///         whole time, which is the shape of this defect: a stale header is a claim about provenance,
///         and provenance is exactly what no amount of testing the data can check.
///     </para>
///     <para>
///         ⚠ <b>Why this is not a glob from the repository root.</b>
///         <c>.claude/worktrees/&lt;agent&gt;</c> holds a whole checkout per parallel agent, including
///         older copies of these very files — so <c>**/Generated/*.g.cs</c> from the root compares two
///         versions of the same table with each other and can agree with itself while the tree it was
///         asked about disagrees. The walk here goes <i>up</i> from the test assembly to the one
///         directory holding this project's own <c>.csproj</c>, which exists once per checkout and is
///         always this one; the two directories are then named outright.
///     </para>
///     <para>
///         ⚠ <b>And it asserts the inventory, not only the agreement.</b> Ask what a version check
///         prints on the day the directory is empty or the path has moved: zero versions all agree
///         with each other, and an empty run is indistinguishable from a clean one. So the files are
///         listed by name rather than discovered, every one of them has to exist, every one has to
///         yield a version, and <see cref="No_generated_artefact_escapes_the_list_that_names_them" />
///         holds the list to the directory in the other direction — a table added without a line here
///         is red rather than silently ungated.
///     </para>
/// </remarks>
public class GeneratedUnicodeVersionTests {
    /// <summary>The ten tables, in <c>Core/Vixen.Ui.Text/Generated</c>.</summary>
    static readonly string[] Tables = [
        "BidiBracketTable.g.cs",
        "BidiClassTable.g.cs",
        "EastAsianWidthTable.g.cs",
        "ExtendedPictographicTable.g.cs",
        "GraphemeBreakTable.g.cs",
        "IndicConjunctTable.g.cs",
        "LineBreakTable.g.cs",
        "ScriptTable.g.cs",
        "SpecialCasingTable.g.cs",
        "WordBreakTable.g.cs"
    ];

    /// <summary>The conformance artefacts, in this project's own <c>Generated</c>.</summary>
    /// <remarks>
    ///     ⚠ <b>Held to the same release as the tables, and that is the half #580 did not ask for.</b>
    ///     A conformance suite from an older UCD than the table it exercises is worse than a stale
    ///     table on its own: it is a green suite proving that the algorithm agrees with a release
    ///     nobody is shipping. These come out of the same generator run, so there is no reason for
    ///     them to differ and no way to notice if they do.
    /// </remarks>
    static readonly string[] Conformance = [
        "BidiCharacterConformance.data",
        "GraphemeBreakConformance.g.cs",
        "LineBreakConformance.data",
        "WordBreakConformance.g.cs"
    ];

    /// <summary>The two header shapes the generator writes a version in.</summary>
    /// <remarks>
    ///     A C# file carries <c>//     version 17.0.0. Do not edit</c> and a data file carries
    ///     <c># Unicode 17.0.0. Generated by …</c>. Both are matched, and a file matching
    ///     <i>neither</i> fails rather than being skipped — a header that has been reworded is a
    ///     file this test has stopped reading, which is the same silence it exists to end.
    /// </remarks>
    static readonly Regex Stated = new(
        @"^(?://\s+version\s+|#\s+Unicode\s+)(?<version>\d+\.\d+\.\d+)",
        RegexOptions.Multiline | RegexOptions.CultureInvariant
    );

    /// <summary>All fourteen artefacts name one and the same Unicode version.</summary>
    [Fact]
    public void Every_generated_artefact_names_the_same_unicode_version() {
        var stated = new List<(string Name, string Version)>();

        foreach (var (directory, names) in Sources()) {
            foreach (var name in names) {
                var path = Path.Combine(directory, name);

                Assert.True(File.Exists(path), $"{name} is missing from {directory} — this list names what the generator writes.");

                var match = Stated.Match(Head(path));

                Assert.True(
                    match.Success,
                    $"{name} states no Unicode version in its header. Either the generator's header was reworded — in "
                    + "which case this test has quietly stopped reading every file and the regex is what needs fixing — "
                    + "or the file is not the generator's."
                );

                stated.Add((name, match.Groups["version"].Value));
            }
        }

        // ⚠ The count, because zero files agreeing is not fourteen files agreeing.
        Assert.Equal(Tables.Length + Conformance.Length, stated.Count);

        var versions = stated.Select(entry => entry.Version).Distinct(StringComparer.Ordinal).ToList();

        Assert.True(
            versions.Count == 1,
            "the generated Unicode artefacts disagree about which UCD release they came from, which means at least one "
            + "of them was regenerated alone: "
            + string.Join(", ", stated.Select(entry => $"{entry.Name} {entry.Version}"))
        );
    }

    /// <summary>Nothing generated sits in either directory without a line in the lists above.</summary>
    /// <remarks>
    ///     ⚠ <b>The other direction, and the one that keeps the lists honest.</b> A list of names
    ///     checked only for existence is a list that can be trimmed to one entry and still pass. This
    ///     is what makes adding an eleventh table a decision rather than an omission — the new file
    ///     is red until it is named, and naming it is what puts it under the version check.
    /// </remarks>
    [Fact]
    public void No_generated_artefact_escapes_the_list_that_names_them() {
        foreach (var (directory, names) in Sources()) {
            var found = Directory.EnumerateFiles(directory)
                .Select(Path.GetFileName)
                .Where(name => name is not null && (name.EndsWith(".g.cs", StringComparison.Ordinal) || name.EndsWith(".data", StringComparison.Ordinal)))
                .Select(name => name!)
                .Order(StringComparer.Ordinal)
                .ToList();

            // ⚠ `ShapingConformance.data` and `VariationConformance.data` are deliberately not here:
            // they come out of `Tools/Vixen.TextRenderingTestGen` and the Consortium's
            // text-rendering-tests rather than out of the UCD, and they state no Unicode version to
            // hold to one. Their headers say which generator wrote them, which is what distinguishes
            // them.
            var mine = found.Where(name => !name.StartsWith("Shaping", StringComparison.Ordinal)
                    && !name.StartsWith("Variation", StringComparison.Ordinal))
                .ToList();

            Assert.Equal(names.Order(StringComparer.Ordinal).ToList(), mine);
        }
    }

    /// <summary>The two directories the generator writes into, with what it writes into each.</summary>
    static (string Directory, string[] Names)[] Sources() {
        var project = Project();

        return [
            (Path.Combine(project.Parent!.FullName, "Vixen.Ui.Text", "Generated"), Tables),
            (Path.Combine(project.FullName, "Generated"), Conformance)
        ];
    }

    /// <summary>This test project's own directory, found by walking up from the assembly.</summary>
    /// <remarks>
    ///     ⚠ Up rather than down, and to a marker that exists exactly once per checkout — see the
    ///     class remark. A search that descended would find a sibling agent's worktree.
    /// </remarks>
    static DirectoryInfo Project() {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent) {
            if (File.Exists(Path.Combine(directory.FullName, "Vixen.Ui.Text.Tests.csproj"))) {
                return directory;
            }
        }

        throw new DirectoryNotFoundException(
            $"Vixen.Ui.Text.Tests.csproj was not found above '{AppContext.BaseDirectory}', so this test cannot say which "
            + "checkout's generated tables it is meant to be reading."
        );
    }

    /// <summary>The first few lines of a file, which is where every one of these states its version.</summary>
    static string Head(string path) => string.Join('\n', File.ReadLines(path).Take(12));
}
