// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Globalization;
using System.Text;

namespace Vixen.Shaders.Generators;

/// <summary>
///     Emits one shader's C# bindings: its keys, and a writer for its constant block.
/// </summary>
/// <remarks>
///     <para>
///         Two things come out, and they answer different questions. The <c>…Keys</c> class answers
///         <em>which</em> — a typed handle per parameter, permutation and resource, so a render
///         feature names <c>LightingKeys.LightCount</c> instead of a string. The <c>…Constants</c>
///         struct and its writer answer <em>where</em> — every offset baked from the reflection, so
///         filling a uniform block is a sequence of stores into a <c>Span&lt;byte&gt;</c> with no
///         name lookup, no reflection and no layout arithmetic at run time.
///     </para>
///     <para>
///         <strong>The offsets are copied, never recomputed.</strong> They come out of the same
///         <c>ShaderLayout</c> pass that told the GLSL and SPIR-V emitters where to put things, so
///         host and shader cannot disagree about <c>float3</c> padding — the failure this whole
///         arrangement exists to make impossible, and one that is invisible when it happens because
///         every byte still lands inside the buffer.
///     </para>
/// </remarks>
static class BindingsEmitter {
    public const string Namespace = "Vixen.Shaders.Generated";

    public static string Emit(string shaderName, ShaderReflection reflection, string source) {
        var writer = new StringBuilder();

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("// Generated by Vixen.Shaders.Generators from " + source + ".");
        writer.AppendLine("// Offsets are Raven's own, copied rather than recomputed. Do not edit.");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();
        writer.AppendLine("using Vixen.Shaders;");
        writer.AppendLine();
        writer.AppendLine($"namespace {Namespace};");
        writer.AppendLine();

        var blocks = UniformBlocks(reflection);

        EmitKeys(writer, shaderName, reflection, blocks);

        foreach (var block in blocks) {
            writer.AppendLine();
            EmitConstants(writer, shaderName, reflection, block, blocks.Length > 1);
        }

        return writer.ToString();
    }

    /// <summary>The four-set convention's name for a set index. See docs/plan/05.</summary>
    /// <remarks>
    ///     A name rather than the number, because <c>PerDrawBlockSize</c> says what it is and
    ///     <c>Set3BlockSize</c> says where it happens to be. A set outside the convention keeps its
    ///     index, which is the honest answer for something the convention has no word for.
    /// </remarks>
    static string SetName(int set) =>
        set switch {
            0 => "PerFrame",
            1 => "PerView",
            2 => "PerMaterial",
            3 => "PerDraw",
            _ => $"Set{set.ToString(System.Globalization.CultureInfo.InvariantCulture)}"
        };

    /// <summary>Every uniform block the shader has — one per set it puts loose uniforms in.</summary>
    /// <remarks>
    ///     <para>
    ///         Was "the one block", because Raven gathers a shader's loose uniforms into a single
    ///         block <em>per set</em> and a shader that marks none of its bindings has one set. A pass
    ///         that says which set each binding is in has up to four, and generating for the first of
    ///         them left three sets' worth of values with no keys at all — reachable only by spelling
    ///         the name out, which is the thing generated bindings exist to avoid.
    ///     </para>
    ///     <para>
    ///         In set order, so the block a single-set shader has is the one that keeps the unadorned
    ///         names.
    ///     </para>
    /// </remarks>
    static UniformBlockInfo[] UniformBlocks(ShaderReflection reflection) =>
        reflection.Sets
            .SelectMany(set => set.Bindings.Select(binding => new UniformBlockInfo(set.Set, binding)))
            .Where(entry => entry.Binding.Type == "UniformBuffer" && entry.Binding.Members.Count > 0)
            .OrderBy(entry => entry.Set)
            .ToArray();

    /// <summary>A uniform block and the set it sits in, which together identify its parameters.</summary>
    /// <remarks>
    ///     Both, not just the binding index: a storage buffer in the same set is a different binding
    ///     with its own member offsets, and filtering on the index alone once mixed the two.
    /// </remarks>
    sealed class UniformBlockInfo(int set, Binding binding) {
        public int Set { get; } = set;
        public Binding Binding { get; } = binding;
    }

    static void EmitKeys(StringBuilder writer, string shaderName, ShaderReflection reflection, UniformBlockInfo[] blocks) {
        writer.AppendLine("/// <summary>");
        writer.AppendLine($"///     Typed keys for shader <c>{Escape(shaderName)}</c>.");
        writer.AppendLine("/// </summary>");
        writer.AppendLine($"public static class {shaderName}Keys {{");
        writer.AppendLine($"    /// <summary>The shader's name, as the effect system asks for it.</summary>");
        writer.AppendLine($"    public const string ShaderName = \"{Escape(shaderName)}\";");

        if (reflection.Permutations.Count > 0) {
            writer.AppendLine();
            writer.AppendLine("    // --- Permutation keys: these select a variant, and changing one recompiles.");

            foreach (var permutation in reflection.Permutations) {
                var type = ShaderTypes.Name(permutation.Type);
                if (type is null) {
                    continue;
                }

                var name = ShaderTypes.Identifier(permutation.Name);
                var value = Literal(permutation.Type, permutation.DefaultValue);
                var used = reflection.UsedPermutationKeys.Contains(permutation.Name, StringComparer.Ordinal);

                writer.AppendLine();

                // Reported rather than filtered on: a key nothing branched on is still a key the
                // material may set, and knowing it changes no output is what keeps a permutation
                // matrix from multiplying by two for nothing.
                writer.AppendLine(
                    used
                        ? "    /// <summary>Affects the generated code, so a distinct value is a distinct variant.</summary>"
                        : "    /// <summary>Declared but unused: setting it produces the same shader.</summary>"
                );

                writer.AppendLine(
                    $"    public static readonly PermutationKey<{type}> {name} = "
                    + $"ParameterKeys.NewPermutation<{type}>({value}, \"{Escape(Qualified(shaderName, permutation.Name))}\");"
                );
            }

            writer.AppendLine();
            writer.AppendLine("    /// <summary>The permutation keys that actually change the generated code.</summary>");
            writer.AppendLine("    public static readonly ParameterKey[] UsedPermutationKeys = [");

            foreach (var permutation in reflection.Permutations) {
                if (reflection.UsedPermutationKeys.Contains(permutation.Name, StringComparer.Ordinal)
                    && ShaderTypes.Name(permutation.Type) is not null) {
                    writer.AppendLine($"        {ShaderTypes.Identifier(permutation.Name)},");
                }
            }

            writer.AppendLine("    ];");
        }

        var resources = reflection.Sets
            .SelectMany(set => set.Bindings.Select(binding => (set.Set, Binding: binding)))
            .Where(entry => entry.Binding.Type is not "UniformBuffer")
            .ToArray();

        if (resources.Length > 0) {
            writer.AppendLine();
            writer.AppendLine("    // --- Resource keys: what the descriptor set is filled from, and where each one goes.");

            foreach (var (set, binding) in resources) {
                if (ResourceType(binding.Type) is not { } type) {
                    continue;
                }

                var name = ShaderTypes.Identifier(binding.Name);

                writer.AppendLine();
                writer.AppendLine($"    /// <summary>set {set}, binding {binding.Index}{(binding.IsWritable ? ", writable" : string.Empty)}.</summary>");
                writer.AppendLine(
                    $"    public static readonly ParameterKey<{type}> {name} = "
                    + $"ParameterKeys.New<{type}>(\"{Escape(Qualified(shaderName, binding.Name))}\");"
                );

                EmitBindingConstants(writer, name, set, binding.Index, binding.Name);
            }
        }

        EmitVertexInputConstants(writer, reflection);

        foreach (var block in blocks) {
            EmitValueKeys(writer, shaderName, reflection, block);
        }

        // The unadorned names describe the first block, which for a shader that marks no sets is its
        // only one — so nothing a single-set shader's callers wrote changes. A shader with more gets a
        // named pair per set as well, because "the constant buffer" stops being a well-formed phrase
        // the moment there are four of them.
        if (blocks.Length > 0) {
            var first = blocks[0];

            writer.AppendLine();
            writer.AppendLine($"    /// <summary>The uniform block's size in bytes — what to allocate.</summary>");
            writer.AppendLine($"    public const int ConstantBufferSize = {first.Binding.Size};");

            EmitBindingConstants(writer, "ConstantBuffer", first.Set, first.Binding.Index, "the uniform block");
        }

        if (blocks.Length > 1) {
            foreach (var block in blocks) {
                var set = SetName(block.Set);

                writer.AppendLine();
                writer.AppendLine($"    /// <summary>Set {block.Set}'s block size in bytes.</summary>");
                writer.AppendLine($"    public const int {set}BlockSize = {block.Binding.Size};");

                EmitBindingConstants(writer, $"{set}Block", block.Set, block.Binding.Index, $"set {block.Set}'s block");
            }
        }

        writer.AppendLine("}");
    }

    /// <summary>
    ///     Where each vertex attribute sits, and how many there are.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         The same argument as <see cref="EmitBindingConstants" />, one interface over: an
    ///         attribute location is the <em>shader's</em> decision, not the host's. Raven's
    ///         <c>StreamPlan</c> locates a stage's own parameters after the shader's streams, so
    ///         <c>position</c> is location 0 in a shader with no streams and location 3 in one with
    ///         three of them — and adding a stream renumbers every attribute under it. A host that
    ///         wrote <c>new(0, VertexFormat.Float32X2, 0)</c> by hand was writing down a number it
    ///         could not see and would not be told about when it moved.
    ///     </para>
    ///     <para>
    ///         What a wrong location produces is worth stating, because it is not a validation
    ///         error: a pipeline whose vertex layout names a location the shader does not declare
    ///         binds nothing to that attribute, and the stage reads whatever the driver left there.
    ///         That is a mesh drawn with its normals in the colour slot, on one driver, silently.
    ///     </para>
    ///     <para>
    ///         Offsets and formats are deliberately <em>not</em> generated. Those come from the
    ///         host's own vertex struct — its field order and its packing — which is exactly the
    ///         half of a vertex layout the shader has no opinion about. Generating them would mean
    ///         inventing a struct layout Raven never saw.
    ///     </para>
    /// </remarks>
    static void EmitVertexInputConstants(StringBuilder writer, ShaderReflection reflection) {
        if (reflection.VertexInputs.Count == 0) {
            return;
        }

        writer.AppendLine();
        writer.AppendLine("    // --- Vertex attributes: where the vertex stage expects each one. See the remarks above.");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>How many attributes the vertex stage takes from a buffer.</summary>");
        writer.AppendLine($"    public const int VertexAttributeCount = {reflection.VertexInputs.Count};");

        foreach (var input in reflection.VertexInputs) {
            writer.AppendLine();
            writer.AppendLine(
                $"    /// <summary>Which location the vertex stage reads <c>{Escape(input.Name)}</c> from.</summary>"
            );

            writer.AppendLine(
                $"    public const uint {ShaderTypes.Identifier(input.Name)}Location = {input.Location};"
            );
        }
    }

    /// <summary>
    ///     Where one binding sits: the set index and the binding index within it.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         The numbers a host has to know and had no way to get. A descriptor write names a
    ///         binding index, and the index is the <em>shader's</em> decision — Raven's
    ///         <c>BindingPlan</c> assigns it from declaration order within a set — so a host that
    ///         wrote one by hand was writing down a number it could not see and would not be told
    ///         about when it changed. Adding a texture above another in the source silently
    ///         renumbers it, and what a wrong index produces is a validation error at best and a
    ///         shader sampling the wrong texture at worst.
    ///     </para>
    ///     <para>
    ///         Constants rather than a lookup, because they are known at compile time and a host
    ///         puts them straight into a <c>DescriptorWrite</c>. <c>uint</c> for the binding to match
    ///         what that takes; <c>int</c> for the set, which is an enum's underlying value.
    ///     </para>
    /// </remarks>
    static void EmitBindingConstants(StringBuilder writer, string name, int set, int binding, string described) {
        writer.AppendLine();
        writer.AppendLine($"    /// <summary>Which descriptor set holds <c>{Escape(described)}</c>.</summary>");
        writer.AppendLine($"    public const int {name}Set = {set};");
        writer.AppendLine();
        writer.AppendLine($"    /// <summary>Which binding within set {set} <c>{Escape(described)}</c> occupies.</summary>");
        writer.AppendLine($"    public const uint {name}Binding = {binding};");
    }

    /// <summary>
    ///     A key per value in the uniform block, alongside the struct that writes the whole thing.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Two ways to fill one block, because two callers want different things. Code that knows
    ///         the shader at compile time wants <c>…Constants</c>: assign fields, call
    ///         <c>Write(Span&lt;byte&gt;)</c>, no lookups. Code that knows it only by <em>name</em> —
    ///         a material read from an asset, a post-process node configured by a compositor document
    ///         — has no generated type to assign to, and needs a <see cref="ParameterKey" /> it can
    ///         set through a <c>ParameterCollection</c>. Without these it interns the key from a
    ///         string, which works and gives up every guarantee interning exists for.
    ///     </para>
    ///     <para>
    ///         <strong>The default comes from the shader.</strong> A key carries its default as bytes,
    ///         and a buffer writer fills the parameters nobody set from it — so emitting
    ///         <c>New&lt;float&gt;(name)</c> where the author wrote <c>= 1f</c> would put a zero where
    ///         they asked for a one, in a block that is otherwise entirely correct.
    ///     </para>
    ///     <para>
    ///         Arrays are skipped: a key's value is written whole, and a shader's array length is a
    ///         ceiling a host fills to a different depth each frame. That case is what
    ///         <c>…Constants</c>' nullable array field is for.
    ///     </para>
    /// </remarks>
    static void EmitValueKeys(
        StringBuilder writer,
        string shaderName,
        ShaderReflection reflection,
        UniformBlockInfo uniforms
    ) {
        var values = reflection.Parameters
            .Where(p => p.Set == uniforms.Set && p.Binding == uniforms.Binding.Index)
            // A leaf of a struct array is skipped for the reason the constants struct skips it: its
            // offset is element zero's, so a key for it would write one element of a table and look
            // like it had written the table.
            .Where(p => !p.Name.Contains("[]"))
            .Where(p => !p.Type.IsArray && !p.Type.IsStruct && ShaderTypes.Name(p.Type) is not null)
            .ToArray();

        if (values.Length == 0) {
            return;
        }

        writer.AppendLine();
        writer.AppendLine("    // --- Value keys: what a name-driven caller fills the block through.");

        foreach (var parameter in values) {
            var type = ShaderTypes.Name(parameter.Type)!;
            var name = ShaderTypes.Identifier(parameter.Name);
            var value = ValueLiteral(parameter.Type, parameter.DefaultValue, type);

            writer.AppendLine();
            writer.AppendLine(
                $"    /// <summary><c>{Escape(parameter.Name)}</c> at byte {parameter.Offset}"
                + (value is null ? string.Empty : $", declared <c>{Escape(parameter.DefaultValue)}</c>")
                + ".</summary>"
            );

            writer.AppendLine(
                $"    public static readonly ParameterKey<{type}> {name} = ParameterKeys.New<{type}>("
                + $"\"{Escape(Qualified(shaderName, parameter.Name))}\""
                + (value is null ? string.Empty : $", {value}")
                + ");"
            );
        }
    }

    static void EmitConstants(
        StringBuilder writer,
        string shaderName,
        ShaderReflection reflection,
        UniformBlockInfo uniforms,
        bool qualify
    ) {
        // One struct per block, and the name says which when there is more than one. A shader with a
        // single block keeps `<Shader>Constants` exactly as it was, because that is every shader that
        // marks no sets.
        var structName = qualify ? $"{shaderName}{SetName(uniforms.Set)}Constants" : $"{shaderName}Constants";

        var owned = reflection.Parameters
            .Where(p => p.Set == uniforms.Set && p.Binding == uniforms.Binding.Index)
            .ToArray();

        // A leaf of a struct array — `lights[].color` — belongs to that array's element type rather
        // than to the block, and gets a struct of its own below.
        var scalars = owned.Where(p => !p.Name.Contains("[]") && ShaderTypes.Name(p.Type) is not null).ToArray();

        var arrays = uniforms.Binding.Members
            .Where(m => m.Type is { IsStruct: true, IsArray: true })
            .ToArray();

        foreach (var array in arrays) {
            EmitElement(writer, shaderName, array, owned);
            writer.AppendLine();
        }

        writer.AppendLine("/// <summary>");
        writer.AppendLine($"///     The values of <c>{Escape(shaderName)}</c>'s uniform block, in C# types.");
        writer.AppendLine("/// </summary>");
        writer.AppendLine("/// <remarks>");
        writer.AppendLine("///     Field order follows the shader's declaration order, not the block's byte order — the");
        writer.AppendLine("///     two differ wherever std140 inserted padding, and the writer knows the difference.");
        writer.AppendLine("/// </remarks>");
        writer.AppendLine($"public struct {structName} {{");

        foreach (var parameter in scalars) {
            var type = ShaderTypes.Name(parameter.Type)!;
            var name = ShaderTypes.Identifier(parameter.Name);

            writer.AppendLine();
            writer.AppendLine($"    /// <summary><c>{Escape(parameter.Name)}</c> at byte {parameter.Offset}.</summary>");

            // An array field is nullable rather than sized: the shader's length is a ceiling the
            // host fills to a different depth each frame, and a null one is "leave it alone", which
            // is what a caller updating one value of a block wants.
            writer.AppendLine(
                parameter.Type.IsArray
                    ? $"    public {type}[]? {name};"
                    : $"    public {type} {name};"
            );
        }

        writer.AppendLine();
        writer.AppendLine("    /// <summary>The block's size in bytes.</summary>");
        writer.AppendLine($"    public const int Size = {uniforms.Binding.Size};");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>Writes every value into <paramref name=\"buffer\"/> at its baked offset.</summary>");
        writer.AppendLine("    /// <exception cref=\"System.ArgumentException\">The buffer is shorter than <see cref=\"Size\"/>.</exception>");
        writer.AppendLine("    public readonly void Write(System.Span<byte> buffer) {");
        writer.AppendLine("        if (buffer.Length < Size) {");
        writer.AppendLine("            throw new System.ArgumentException(");
        writer.AppendLine($"                $\"A {structName} block needs {{Size}} bytes; this one has {{buffer.Length}}.\",");
        writer.AppendLine("                nameof(buffer)");
        writer.AppendLine("            );");
        writer.AppendLine("        }");

        foreach (var parameter in scalars) {
            writer.AppendLine();
            EmitStore(writer, parameter);
        }

        writer.AppendLine("    }");
        writer.AppendLine("}");
    }

    /// <summary>Emits the element type of a struct array, and a writer that places one element.</summary>
    /// <remarks>
    ///     <para>
    ///         A struct array could have been four parallel arrays — one per field, which is the
    ///         shape the flattened reflection arrives in — and that would have been honest to the
    ///         layout and awful to use: filling a light list would mean four arrays kept in step by
    ///         hand. One element struct with an indexed writer is the same bytes and the loop a
    ///         caller was going to write anyway.
    ///     </para>
    ///     <para>
    ///         Indexed rather than taking the whole array, because the count is the host's each
    ///         frame: a light list sized for sixteen is filled to however many reached this draw,
    ///         and the elements past that are not zeroed but simply not read — <c>lightCount</c> is
    ///         what stops the shader looking at them.
    ///     </para>
    /// </remarks>
    static void EmitElement(StringBuilder writer, string shaderName, Member array, Parameter[] owned) {
        var prefix = array.Name + "[].";
        var fields = owned
            .Where(p => p.Name.StartsWith(prefix, StringComparison.Ordinal) && ShaderTypes.Name(p.Type) is not null)
            .ToArray();

        if (fields.Length == 0) {
            return;
        }

        var name = $"{shaderName}{ShaderTypes.Identifier(array.Name)}Element";
        var count = array.Type.ArrayLength ?? 0;

        writer.AppendLine("/// <summary>");
        writer.AppendLine($"///     One element of <c>{Escape(shaderName)}.{Escape(array.Name)}</c>.");
        writer.AppendLine("/// </summary>");
        writer.AppendLine($"public struct {name} {{");

        foreach (var field in fields) {
            writer.AppendLine();
            writer.AppendLine(
                $"    /// <summary><c>{Escape(field.Name)}</c> — {field.Size} bytes at "
                + $"{field.Offset - array.Offset} into the element.</summary>"
            );
            writer.AppendLine($"    public {ShaderTypes.Name(field.Type)!} {ShaderTypes.Identifier(field.Name.Substring(prefix.Length))};");
        }

        writer.AppendLine();
        writer.AppendLine("    /// <summary>How many elements the shader declared room for.</summary>");
        writer.AppendLine($"    public const int Count = {count};");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>Bytes from one element to the next.</summary>");
        writer.AppendLine($"    public const int Stride = {array.ArrayStride};");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>Byte offset of element zero within the block.</summary>");
        writer.AppendLine($"    public const int BaseOffset = {array.Offset};");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>Writes this element into slot <paramref name=\"index\"/>.</summary>");
        writer.AppendLine("    /// <exception cref=\"System.ArgumentOutOfRangeException\">The slot is outside the declared array.</exception>");
        writer.AppendLine("    public readonly void Write(System.Span<byte> buffer, int index) {");
        writer.AppendLine("        System.ArgumentOutOfRangeException.ThrowIfNegative(index);");
        writer.AppendLine("        System.ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(index, Count);");
        writer.AppendLine();
        writer.AppendLine("        var at = BaseOffset + index * Stride;");

        foreach (var field in fields) {
            var member = ShaderTypes.Identifier(field.Name.Substring(prefix.Length));
            var relative = field.Offset - array.Offset;
            var modifier = ByValue(field.Type) ? string.Empty : "in ";

            writer.AppendLine();
            writer.AppendLine($"        // {field.Name}, {relative} bytes into the element.");
            writer.AppendLine($"        ShaderConstants.Write(buffer, at + {relative}, {modifier}{member});");
        }

        writer.AppendLine("    }");
        writer.AppendLine("}");
    }

    static void EmitStore(StringBuilder writer, Parameter parameter) {
        var type = ShaderTypes.Name(parameter.Type)!;
        var name = ShaderTypes.Identifier(parameter.Name);
        var comment = $"        // {parameter.Name}";

        if (parameter.Type.IsArray) {
            var count = parameter.Type.ArrayLength ?? 0;

            writer.AppendLine($"{comment}: {count} × {parameter.ArrayStride} bytes apart.");
            writer.AppendLine($"        if ({name} is not null) {{");
            writer.AppendLine(
                $"            ShaderConstants.WriteArray<{type}>(buffer, {parameter.Offset}, "
                + $"{parameter.ArrayStride}, {count}, {name});"
            );
            writer.AppendLine("        }");
            return;
        }

        var scalarModifier = ByValue(parameter.Type) ? string.Empty : "in ";

        writer.AppendLine($"{comment}, {parameter.Size} bytes.");
        writer.AppendLine(
            ShaderTypes.NeedsColumnStride(parameter.Type)
                ? $"        ShaderConstants.Write(buffer, {parameter.Offset}, in {name}, {parameter.MatrixStride});"
                : $"        ShaderConstants.Write(buffer, {parameter.Offset}, {scalarModifier}{name});"
        );
    }

    static bool ByValue(DataType type) => type.Rows == 1 && !type.IsMatrix;

    static string? ResourceType(string descriptor) =>
        descriptor switch {
            "SampledTexture" or "StorageImage" => "global::Vixen.Graphics.TextureViewHandle",
            "Sampler" => "global::Vixen.Graphics.SamplerHandle",
            "StorageBuffer" or "UniformBuffer" => "global::Vixen.Graphics.BufferHandle",
            _ => null
        };

    /// <summary>The shader's dotted name for a parameter, which is what the key is interned under.</summary>
    static string Qualified(string shaderName, string parameter) => $"{shaderName}.{parameter}";

    /// <summary>Renders a permutation default as a C# literal of its own type.</summary>
    static string Literal(DataType type, string value) =>
        type.Scalar switch {
            "Bool" => string.Equals(value, "true", StringComparison.OrdinalIgnoreCase) ? "true" : "false",
            "UInt" => (uint.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var u) ? u : 0u)
                .ToString(CultureInfo.InvariantCulture) + "u",
            _ => (int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var i) ? i : 0)
                .ToString(CultureInfo.InvariantCulture)
        };

    /// <summary>
    ///     A uniform's declared default as a C# literal, or null when there is nothing to spell.
    /// </summary>
    /// <remarks>
    ///     <para>
    ///         Scalars <em>and vectors</em>. It used to be scalars only, and the reason given was true
    ///         at the time: a non-const field's default came from a literal initialiser and
    ///         <c>float2(0.001f, 0.001f)</c> is a call, so Raven reported nothing for it. Raven folds
    ///         a vector construction now — see <c>ConstantEvaluator.EvaluateVector</c> — and reports
    ///         the lanes comma separated, so refusing them here would be this end of the pipe throwing
    ///         away what the other end just learned to say.
    ///     </para>
    ///     <para>
    ///         ⚠ <b>What that silence cost.</b> A key with no default leaves
    ///         <c>ParameterKey.DefaultBytes</c> empty, and <c>EffectConstants</c> writes zeros for
    ///         every member a host did not mention. <c>ParticleSprite.tint</c> declares
    ///         <c>float4(1f, 1f, 1f, 1f)</c> and arrived as <c>(0, 0, 0, 0)</c>: black at zero alpha,
    ///         invisible under an additive blend. <c>Bloom.texelSize</c> has the same declaration and
    ///         never showed it, because that renderer writes the parameter every frame.
    ///     </para>
    ///     <para>
    ///         Null rather than a zero literal when the text is absent or unparsable — the key then
    ///         carries <c>default(T)</c>, which is honestly "nobody said". Matrices and arrays stay
    ///         out: neither has a constructor taking its elements in order, so neither has a literal
    ///         to spell.
    ///     </para>
    /// </remarks>
    static string? ValueLiteral(DataType type, string value, string typeName) {
        if (string.IsNullOrEmpty(value) || type.IsArray || type.IsMatrix || type.Columns != 1) {
            return null;
        }

        // ⚠ A vector's lane count is its **rows**: `float4` reflects as `Rows: 4, Columns: 1`, and a
        // `Columns` of anything but one is a matrix. Reading the width off `Columns` looks right,
        // matches the word "vector" in every other API, and rejects every vector there is.
        if (type.Rows > 1) {
            return VectorLiteral(type, value, typeName);
        }

        if (type.Rows != 1) {
            return null;
        }

        return type.Scalar switch {
            "Bool" when bool.TryParse(value, out var b) => b ? "true" : "false",
            "Int" when int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var i) =>
                i.ToString(CultureInfo.InvariantCulture),
            "UInt" when uint.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var u) =>
                u.ToString(CultureInfo.InvariantCulture) + "u",
            "Float" when float.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var f) =>
                f.ToString("R", CultureInfo.InvariantCulture) + "f",
            "Double" when double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var d) =>
                d.ToString("R", CultureInfo.InvariantCulture) + "d",
            _ => null
        };
    }

    /// <summary>A vector's declared default as a C# constructor call, or null when it will not spell.</summary>
    /// <remarks>
    ///     <para>
    ///         ⚠ <b>Every lane or none.</b> Raven writes the lanes comma separated and folds a
    ///         broadcast — <c>float3(0f)</c> — into three of them before it gets here, so a count that
    ///         does not match the declared width means the two ends disagree about the shape rather
    ///         than that a lane was omitted. Emitting a partial vector would fill some lanes from the
    ///         shader and leave the rest at zero, which is a default that is wrong in a way nobody
    ///         would look for.
    ///     </para>
    ///     <para>
    ///         The type name is the one the key is declared with, so the constructor is the same
    ///         <c>Vixen.Core.Mathematics</c> type on both sides of the assignment and this does not
    ///         have to know which vector it is.
    ///     </para>
    /// </remarks>
    static string? VectorLiteral(DataType type, string value, string typeName) {
        var lanes = value.Split(',');

        if (lanes.Length != type.Rows) {
            return null;
        }

        var spelled = new string[lanes.Length];

        for (var lane = 0; lane < lanes.Length; lane++) {
            // Through the scalar path, so a lane is parsed and re-formatted by the same code a scalar
            // default is — one place that decides what `1` means for a float, and one place to fix
            // when a scalar type is added. A fresh `DataType` rather than a `with`, because this one
            // is a mutable class and copying it would alias the caller's.
            var scalar = new DataType { Scalar = type.Scalar, Rows = 1, Columns = 1 };

            if (ValueLiteral(scalar, lanes[lane].Trim(), typeName) is not { } one) {
                return null;
            }

            spelled[lane] = one;
        }

        return $"new {typeName}({string.Join(", ", spelled)})";
    }

    static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
