// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Globalization;
using System.Text;

namespace Vixen.Shaders.Generators;

/// <summary>
///     Emits one shader's C# bindings: its keys, and a writer for its constant block.
/// </summary>
/// <remarks>
///     <para>
///         Two things come out, and they answer different questions. The <c>…Keys</c> class answers
///         <em>which</em> — a typed handle per parameter, permutation and resource, so a render
///         feature names <c>LightingKeys.LightCount</c> instead of a string. The <c>…Constants</c>
///         struct and its writer answer <em>where</em> — every offset baked from the reflection, so
///         filling a uniform block is a sequence of stores into a <c>Span&lt;byte&gt;</c> with no
///         name lookup, no reflection and no layout arithmetic at run time.
///     </para>
///     <para>
///         <strong>The offsets are copied, never recomputed.</strong> They come out of the same
///         <c>ShaderLayout</c> pass that told the GLSL and SPIR-V emitters where to put things, so
///         host and shader cannot disagree about <c>float3</c> padding — the failure this whole
///         arrangement exists to make impossible, and one that is invisible when it happens because
///         every byte still lands inside the buffer.
///     </para>
/// </remarks>
static class BindingsEmitter {
    public const string Namespace = "Vixen.Shaders.Generated";

    public static string Emit(string shaderName, ShaderReflection reflection, string source) {
        var writer = new StringBuilder();

        writer.AppendLine("// <auto-generated/>");
        writer.AppendLine("// Generated by Vixen.Shaders.Generators from " + source + ".");
        writer.AppendLine("// Offsets are Raven's own, copied rather than recomputed. Do not edit.");
        writer.AppendLine("#nullable enable");
        writer.AppendLine();
        writer.AppendLine("using Vixen.Shaders;");
        writer.AppendLine();
        writer.AppendLine($"namespace {Namespace};");
        writer.AppendLine();

        var uniforms = UniformBlock(reflection);

        EmitKeys(writer, shaderName, reflection, uniforms);

        if (uniforms is not null) {
            writer.AppendLine();
            EmitConstants(writer, shaderName, reflection, uniforms);
        }

        return writer.ToString();
    }

    /// <summary>The one uniform block a shader's loose uniforms are gathered into, if it has any.</summary>
    /// <remarks>
    ///     Raven puts every loose uniform of a shader into a single block, so there is at most one —
    ///     which is what lets the generated writer be <c>Write(Span&lt;byte&gt;)</c> on one struct
    ///     rather than one method per block with the caller choosing.
    /// </remarks>
    static UniformBlockInfo? UniformBlock(ShaderReflection reflection) =>
        reflection.Sets
            .SelectMany(set => set.Bindings.Select(binding => new UniformBlockInfo(set.Set, binding)))
            .FirstOrDefault(entry => entry.Binding.Type == "UniformBuffer" && entry.Binding.Members.Count > 0);

    /// <summary>A uniform block and the set it sits in, which together identify its parameters.</summary>
    /// <remarks>
    ///     Both, not just the binding index: a storage buffer in the same set is a different binding
    ///     with its own member offsets, and filtering on the index alone once mixed the two.
    /// </remarks>
    sealed class UniformBlockInfo(int set, Binding binding) {
        public int Set { get; } = set;
        public Binding Binding { get; } = binding;
    }

    static void EmitKeys(StringBuilder writer, string shaderName, ShaderReflection reflection, UniformBlockInfo? uniforms) {
        writer.AppendLine("/// <summary>");
        writer.AppendLine($"///     Typed keys for shader <c>{Escape(shaderName)}</c>.");
        writer.AppendLine("/// </summary>");
        writer.AppendLine($"public static class {shaderName}Keys {{");
        writer.AppendLine($"    /// <summary>The shader's name, as the effect system asks for it.</summary>");
        writer.AppendLine($"    public const string ShaderName = \"{Escape(shaderName)}\";");

        if (reflection.Permutations.Count > 0) {
            writer.AppendLine();
            writer.AppendLine("    // --- Permutation keys: these select a variant, and changing one recompiles.");

            foreach (var permutation in reflection.Permutations) {
                var type = ShaderTypes.Name(permutation.Type);
                if (type is null) {
                    continue;
                }

                var name = ShaderTypes.Identifier(permutation.Name);
                var value = Literal(permutation.Type, permutation.DefaultValue);
                var used = reflection.UsedPermutationKeys.Contains(permutation.Name, StringComparer.Ordinal);

                writer.AppendLine();

                // Reported rather than filtered on: a key nothing branched on is still a key the
                // material may set, and knowing it changes no output is what keeps a permutation
                // matrix from multiplying by two for nothing.
                writer.AppendLine(
                    used
                        ? "    /// <summary>Affects the generated code, so a distinct value is a distinct variant.</summary>"
                        : "    /// <summary>Declared but unused: setting it produces the same shader.</summary>"
                );

                writer.AppendLine(
                    $"    public static readonly PermutationKey<{type}> {name} = "
                    + $"ParameterKeys.NewPermutation<{type}>({value}, \"{Escape(Qualified(shaderName, permutation.Name))}\");"
                );
            }

            writer.AppendLine();
            writer.AppendLine("    /// <summary>The permutation keys that actually change the generated code.</summary>");
            writer.AppendLine("    public static readonly ParameterKey[] UsedPermutationKeys = [");

            foreach (var permutation in reflection.Permutations) {
                if (reflection.UsedPermutationKeys.Contains(permutation.Name, StringComparer.Ordinal)
                    && ShaderTypes.Name(permutation.Type) is not null) {
                    writer.AppendLine($"        {ShaderTypes.Identifier(permutation.Name)},");
                }
            }

            writer.AppendLine("    ];");
        }

        var resources = reflection.Sets
            .SelectMany(set => set.Bindings.Select(binding => (set.Set, Binding: binding)))
            .Where(entry => entry.Binding.Type is not "UniformBuffer")
            .ToArray();

        if (resources.Length > 0) {
            writer.AppendLine();
            writer.AppendLine("    // --- Resource keys: what the descriptor set is filled from.");

            foreach (var (set, binding) in resources) {
                if (ResourceType(binding.Type) is not { } type) {
                    continue;
                }

                writer.AppendLine();
                writer.AppendLine($"    /// <summary>set {set}, binding {binding.Index}{(binding.IsWritable ? ", writable" : string.Empty)}.</summary>");
                writer.AppendLine(
                    $"    public static readonly ParameterKey<{type}> {ShaderTypes.Identifier(binding.Name)} = "
                    + $"ParameterKeys.New<{type}>(\"{Escape(Qualified(shaderName, binding.Name))}\");"
                );
            }
        }

        if (uniforms is not null) {
            writer.AppendLine();
            writer.AppendLine($"    /// <summary>The uniform block's size in bytes — what to allocate.</summary>");
            writer.AppendLine($"    public const int ConstantBufferSize = {uniforms.Binding.Size};");
        }

        writer.AppendLine("}");
    }

    static void EmitConstants(
        StringBuilder writer,
        string shaderName,
        ShaderReflection reflection,
        UniformBlockInfo uniforms
    ) {
        var owned = reflection.Parameters
            .Where(p => p.Set == uniforms.Set && p.Binding == uniforms.Binding.Index)
            .ToArray();

        // A leaf of a struct array — `lights[].color` — belongs to that array's element type rather
        // than to the block, and gets a struct of its own below.
        var scalars = owned.Where(p => !p.Name.Contains("[]") && ShaderTypes.Name(p.Type) is not null).ToArray();

        var arrays = uniforms.Binding.Members
            .Where(m => m.Type is { IsStruct: true, IsArray: true })
            .ToArray();

        foreach (var array in arrays) {
            EmitElement(writer, shaderName, array, owned);
            writer.AppendLine();
        }

        writer.AppendLine("/// <summary>");
        writer.AppendLine($"///     The values of <c>{Escape(shaderName)}</c>'s uniform block, in C# types.");
        writer.AppendLine("/// </summary>");
        writer.AppendLine("/// <remarks>");
        writer.AppendLine("///     Field order follows the shader's declaration order, not the block's byte order — the");
        writer.AppendLine("///     two differ wherever std140 inserted padding, and the writer knows the difference.");
        writer.AppendLine("/// </remarks>");
        writer.AppendLine($"public struct {shaderName}Constants {{");

        foreach (var parameter in scalars) {
            var type = ShaderTypes.Name(parameter.Type)!;
            var name = ShaderTypes.Identifier(parameter.Name);

            writer.AppendLine();
            writer.AppendLine($"    /// <summary><c>{Escape(parameter.Name)}</c> at byte {parameter.Offset}.</summary>");

            // An array field is nullable rather than sized: the shader's length is a ceiling the
            // host fills to a different depth each frame, and a null one is "leave it alone", which
            // is what a caller updating one value of a block wants.
            writer.AppendLine(
                parameter.Type.IsArray
                    ? $"    public {type}[]? {name};"
                    : $"    public {type} {name};"
            );
        }

        writer.AppendLine();
        writer.AppendLine("    /// <summary>The block's size in bytes.</summary>");
        writer.AppendLine($"    public const int Size = {uniforms.Binding.Size};");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>Writes every value into <paramref name=\"buffer\"/> at its baked offset.</summary>");
        writer.AppendLine("    /// <exception cref=\"System.ArgumentException\">The buffer is shorter than <see cref=\"Size\"/>.</exception>");
        writer.AppendLine("    public readonly void Write(System.Span<byte> buffer) {");
        writer.AppendLine("        if (buffer.Length < Size) {");
        writer.AppendLine("            throw new System.ArgumentException(");
        writer.AppendLine($"                $\"A {shaderName} constant buffer needs {{Size}} bytes; this one has {{buffer.Length}}.\",");
        writer.AppendLine("                nameof(buffer)");
        writer.AppendLine("            );");
        writer.AppendLine("        }");

        foreach (var parameter in scalars) {
            writer.AppendLine();
            EmitStore(writer, parameter);
        }

        writer.AppendLine("    }");
        writer.AppendLine("}");
    }

    /// <summary>Emits the element type of a struct array, and a writer that places one element.</summary>
    /// <remarks>
    ///     <para>
    ///         A struct array could have been four parallel arrays — one per field, which is the
    ///         shape the flattened reflection arrives in — and that would have been honest to the
    ///         layout and awful to use: filling a light list would mean four arrays kept in step by
    ///         hand. One element struct with an indexed writer is the same bytes and the loop a
    ///         caller was going to write anyway.
    ///     </para>
    ///     <para>
    ///         Indexed rather than taking the whole array, because the count is the host's each
    ///         frame: a light list sized for sixteen is filled to however many reached this draw,
    ///         and the elements past that are not zeroed but simply not read — <c>lightCount</c> is
    ///         what stops the shader looking at them.
    ///     </para>
    /// </remarks>
    static void EmitElement(StringBuilder writer, string shaderName, Member array, Parameter[] owned) {
        var prefix = array.Name + "[].";
        var fields = owned
            .Where(p => p.Name.StartsWith(prefix, StringComparison.Ordinal) && ShaderTypes.Name(p.Type) is not null)
            .ToArray();

        if (fields.Length == 0) {
            return;
        }

        var name = $"{shaderName}{ShaderTypes.Identifier(array.Name)}Element";
        var count = array.Type.ArrayLength ?? 0;

        writer.AppendLine("/// <summary>");
        writer.AppendLine($"///     One element of <c>{Escape(shaderName)}.{Escape(array.Name)}</c>.");
        writer.AppendLine("/// </summary>");
        writer.AppendLine($"public struct {name} {{");

        foreach (var field in fields) {
            writer.AppendLine();
            writer.AppendLine(
                $"    /// <summary><c>{Escape(field.Name)}</c> — {field.Size} bytes at "
                + $"{field.Offset - array.Offset} into the element.</summary>"
            );
            writer.AppendLine($"    public {ShaderTypes.Name(field.Type)!} {ShaderTypes.Identifier(field.Name.Substring(prefix.Length))};");
        }

        writer.AppendLine();
        writer.AppendLine("    /// <summary>How many elements the shader declared room for.</summary>");
        writer.AppendLine($"    public const int Count = {count};");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>Bytes from one element to the next.</summary>");
        writer.AppendLine($"    public const int Stride = {array.ArrayStride};");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>Byte offset of element zero within the block.</summary>");
        writer.AppendLine($"    public const int BaseOffset = {array.Offset};");
        writer.AppendLine();
        writer.AppendLine("    /// <summary>Writes this element into slot <paramref name=\"index\"/>.</summary>");
        writer.AppendLine("    /// <exception cref=\"System.ArgumentOutOfRangeException\">The slot is outside the declared array.</exception>");
        writer.AppendLine("    public readonly void Write(System.Span<byte> buffer, int index) {");
        writer.AppendLine("        System.ArgumentOutOfRangeException.ThrowIfNegative(index);");
        writer.AppendLine("        System.ArgumentOutOfRangeException.ThrowIfGreaterThanOrEqual(index, Count);");
        writer.AppendLine();
        writer.AppendLine("        var at = BaseOffset + index * Stride;");

        foreach (var field in fields) {
            var member = ShaderTypes.Identifier(field.Name.Substring(prefix.Length));
            var relative = field.Offset - array.Offset;
            var modifier = ByValue(field.Type) ? string.Empty : "in ";

            writer.AppendLine();
            writer.AppendLine($"        // {field.Name}, {relative} bytes into the element.");
            writer.AppendLine($"        ShaderConstants.Write(buffer, at + {relative}, {modifier}{member});");
        }

        writer.AppendLine("    }");
        writer.AppendLine("}");
    }

    static void EmitStore(StringBuilder writer, Parameter parameter) {
        var type = ShaderTypes.Name(parameter.Type)!;
        var name = ShaderTypes.Identifier(parameter.Name);
        var comment = $"        // {parameter.Name}";

        if (parameter.Type.IsArray) {
            var count = parameter.Type.ArrayLength ?? 0;

            writer.AppendLine($"{comment}: {count} × {parameter.ArrayStride} bytes apart.");
            writer.AppendLine($"        if ({name} is not null) {{");
            writer.AppendLine(
                $"            ShaderConstants.WriteArray<{type}>(buffer, {parameter.Offset}, "
                + $"{parameter.ArrayStride}, {count}, {name});"
            );
            writer.AppendLine("        }");
            return;
        }

        var scalarModifier = ByValue(parameter.Type) ? string.Empty : "in ";

        writer.AppendLine($"{comment}, {parameter.Size} bytes.");
        writer.AppendLine(
            ShaderTypes.NeedsColumnStride(parameter.Type)
                ? $"        ShaderConstants.Write(buffer, {parameter.Offset}, in {name}, {parameter.MatrixStride});"
                : $"        ShaderConstants.Write(buffer, {parameter.Offset}, {scalarModifier}{name});"
        );
    }

    static bool ByValue(DataType type) => type.Rows == 1 && !type.IsMatrix;

    static string? ResourceType(string descriptor) =>
        descriptor switch {
            "SampledTexture" or "StorageImage" => "global::Vixen.Graphics.TextureViewHandle",
            "Sampler" => "global::Vixen.Graphics.SamplerHandle",
            "StorageBuffer" or "UniformBuffer" => "global::Vixen.Graphics.BufferHandle",
            _ => null
        };

    /// <summary>The shader's dotted name for a parameter, which is what the key is interned under.</summary>
    static string Qualified(string shaderName, string parameter) => $"{shaderName}.{parameter}";

    /// <summary>Renders a permutation default as a C# literal of its own type.</summary>
    static string Literal(DataType type, string value) =>
        type.Scalar switch {
            "Bool" => string.Equals(value, "true", StringComparison.OrdinalIgnoreCase) ? "true" : "false",
            "UInt" => (uint.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var u) ? u : 0u)
                .ToString(CultureInfo.InvariantCulture) + "u",
            _ => (int.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var i) ? i : 0)
                .ToString(CultureInfo.InvariantCulture)
        };

    static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
