// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

namespace Vixen.Raven.Parsing;

/// <summary>
///     Lexical token vocabulary for the hand-written lexer — the same shape the
///     retired ANTLR vocabulary had, because the parser needs lexical identity
///     (<c>=</c> versus <c>==</c> versus <c>=&gt;</c>) while the tree's
///     <see cref="Syntax.SyntaxKind" /> for a token is chosen by context (an
///     <c>=</c> is an <c>EqualsToken</c> in an initializer and an
///     <c>OperatorToken</c> in an assignment expression).
/// </summary>
public enum RavenTokenKind {
    None,
    EndOfFile,
    NewLine,

    // Trivia
    Whitespace,
    SingleLineComment,
    MultiLineComment,

    // Identifiers and literals
    Identifier,
    IntegerLiteral,
    HexIntegerLiteral,
    BinIntegerLiteral,
    RealLiteral,
    StringLiteral,

    // Keywords
    GetKeyword,
    SetKeyword,
    WillSetKeyword,
    DidSetKeyword,
    FuncKeyword,
    ProtocolKeyword,
    SelfKeyword,
    ShaderKeyword,
    StructKeyword,
    VarKeyword,
    ValKeyword,
    RepeatKeyword,
    ImportKeyword,
    PackageKeyword,
    InitKeyword,
    BaseKeyword,
    BreakKeyword,
    CaseKeyword,
    ContinueKeyword,
    DefaultKeyword,
    DiscardKeyword,
    ElseKeyword,
    EnumKeyword,
    FalseKeyword,
    ForKeyword,
    IfKeyword,
    InKeyword,
    OperatorKeyword,
    ReturnKeyword,
    SwitchKeyword,
    TrueKeyword,
    WhileKeyword,
    WhereKeyword,
    ComposeKeyword,
    ConstKeyword,
    OverrideKeyword,
    ReadOnlyKeyword,
    StaticKeyword,
    StreamKeyword,
    GroupSharedKeyword,
    InOutKeyword,

    // Predefined type keywords
    BoolKeyword,
    Bool2Keyword,
    Bool3Keyword,
    Bool4Keyword,
    IntKeyword,
    Int2Keyword,
    Int3Keyword,
    Int4Keyword,
    UIntKeyword,
    UInt2Keyword,
    UInt3Keyword,
    UInt4Keyword,
    FloatKeyword,
    Float2Keyword,
    Float3Keyword,
    Float4Keyword,
    DoubleKeyword,
    Double2Keyword,
    Double3Keyword,
    Double4Keyword,
    Mat2Keyword,
    Mat2x3Keyword,
    Mat2x4Keyword,
    Mat3Keyword,
    Mat3x2Keyword,
    Mat3x4Keyword,
    Mat4Keyword,
    Mat4x2Keyword,
    Mat4x3Keyword,

    // Punctuation
    OpenBrace,
    CloseBrace,
    OpenBracket,
    CloseBracket,
    OpenParen,
    CloseParen,
    Dot,
    DotDot,
    Comma,
    Colon,
    Question,
    Arrow,

    // Operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Ampersand,
    Bar,
    Caret,
    Bang,
    Tilde,
    Equals,
    LessThan,
    GreaterThan,
    PlusPlus,
    MinusMinus,
    AmpersandAmpersand,
    BarBar,
    EqualsEquals,
    BangEquals,
    LessThanEquals,
    GreaterThanEquals,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    PercentEquals,
    AmpersandEquals,
    BarEquals,
    CaretEquals,
    LessThanLessThan,
    LessThanLessThanEquals,
    GreaterThanGreaterThan,
    GreaterThanGreaterThanEquals,
    UnsignedShiftRight,
    UnsignedShiftRightEquals
}
