// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Text.Json;
using Vixen.Core.Serialization;
using Vixen.Graphics;
using Vixen.ShaderCompiler;
using Vixen.Shaders;
using Xunit;

namespace Tests;

/// <summary>
///     Compiling a variant, and enumerating the ones a shader has — docs/plan/06 § Effect
///     permutations, tier three.
/// </summary>
/// <remarks>
///     The oracle throughout is <c>Lighting.reflect.json</c>, which is Raven's own description of the
///     same shader, checked in beside it and regenerated by a documented command. Asserting the
///     translation against it rather than against numbers typed here is what makes these tests notice
///     a change in the compiler instead of merely surviving one.
/// </remarks>
public class EffectCompilerTests {
    static string Fixture(string name) => Path.Combine(AppContext.BaseDirectory, "Fixtures", name);

    /// <summary>The layout fixture, compiled to GLSL.</summary>
    /// <remarks>
    ///     GLSL rather than SPIR-V because the fixture declares a <c>bool</c> uniform, and the SPIR-V
    ///     backend refuses one (RVN4001) — correctly: std140 gives it four bytes and SPIR-V has no
    ///     four-byte boolean to put there. It is in the fixture because the <em>layout</em> rules
    ///     treat it specially, which is what that shader is for. Everything asserted here is the
    ///     reflection and the record, both of which are the same on either backend by construction;
    ///     <see cref="Nested" /> is the one that goes all the way to SPIR-V.
    /// </remarks>
    static RavenEffectCompiler Lighting() => new([Fixture("Lighting.rvn")], "glsl");

    /// <summary>The dependent-permutation fixture, compiled to SPIR-V.</summary>
    static RavenEffectCompiler Nested() => new([Fixture("Nested.rvn")]);

    static JsonElement Reflection => JsonDocument.Parse(File.ReadAllText(Fixture("Lighting.reflect.json"))).RootElement;

    static EffectKey Key(bool shadows) =>
        EffectKey.Of("Lighting", [new("Lighting.UseShadows", shadows ? "true" : "false"), new("Lighting.MaxLights", "4")]);

    // --- The translation ----------------------------------------------------

    /// <summary>A variant comes out with modules in it.</summary>
    [Fact]
    public void A_variant_compiles_to_bytecode() {
        var effect = Lighting().TryGet(Key(shadows: true));

        Assert.NotNull(effect);
        Assert.Equal("Lighting", effect.ShaderName);
        Assert.Equal("glsl", effect.Target);
        Assert.NotEmpty(effect.SourceHash);

        Assert.Equal(
            [ShaderStage.Vertex, ShaderStage.Fragment],
            effect.Stages.Select(stage => stage.Stage).Order()
        );

        Assert.All(effect.Stages, stage => Assert.NotEmpty(stage.Bytecode));
    }

    /// <summary>Two variants of one shader are two different modules.</summary>
    /// <remarks>
    ///     The claim a permutation key makes. Without it the whole cache is an elaborate way of
    ///     compiling one shader and filing it under several names.
    /// </remarks>
    [Fact]
    public void Two_variants_are_different_code() {
        var compiler = Lighting();

        var on = compiler.TryGet(Key(shadows: true))!;
        var off = compiler.TryGet(Key(shadows: false))!;

        Assert.NotEqual(on.ToKey(), off.ToKey());

        Assert.NotEqual(
            on.Stages.Single(stage => stage.Stage == ShaderStage.Fragment).Bytecode,
            off.Stages.Single(stage => stage.Stage == ShaderStage.Fragment).Bytecode
        );
    }

    /// <summary>
    ///     Every offset the record carries is the offset Raven reported.
    /// </summary>
    /// <remarks>
    ///     The differential test. A host writes a value at the offset in this record, so an offset
    ///     that drifted from the compiler's own by four bytes is a parameter written into the one
    ///     beside it — which shows up as a slightly wrong image and no error at all.
    /// </remarks>
    [Fact]
    public void The_record_carries_the_reflections_own_offsets() {
        var effect = Lighting().TryGet(Key(shadows: false))!;

        foreach (var parameter in Reflection.GetProperty("Parameters").EnumerateArray()) {
            var name = parameter.GetProperty("Name").GetString()!;

            // A struct-array leaf is expanded, and is checked by its own test below.
            if (name.Contains("[]", StringComparison.Ordinal)) {
                continue;
            }

            // The uniform block's own values, not the storage buffer's. `overflow.position` is a
            // member of a Buffer<PunctualLight> in the same set, at offset 0 of a different buffer —
            // and the flat parameter list holds both, which is exactly why the filter is on set and
            // binding rather than on set alone.
            if (parameter.GetProperty("Binding").GetInt32() != 0) {
                continue;
            }

            var translated = effect.Parameters.SingleOrDefault(candidate => candidate.Name == "Lighting." + name);

            Assert.NotNull(translated);
            Assert.Equal(parameter.GetProperty("Offset").GetInt32(), translated.Offset);
            Assert.Equal(parameter.GetProperty("Size").GetInt32(), translated.Size);
        }
    }

    /// <summary>Every binding the reflection describes is somewhere a descriptor set can be built from.</summary>
    [Fact]
    public void The_record_carries_the_reflections_own_bindings() {
        var effect = Lighting().TryGet(Key(shadows: false))!;

        foreach (var set in Reflection.GetProperty("Sets").EnumerateArray()) {
            foreach (var binding in set.GetProperty("Bindings").EnumerateArray()) {
                var translated = effect.Bindings.Single(candidate => candidate.Name == binding.GetProperty("Name").GetString());

                Assert.Equal((DescriptorSetSlot)set.GetProperty("Set").GetInt32(), translated.Set);
                Assert.Equal((uint)binding.GetProperty("Binding").GetInt32(), translated.Binding);
                Assert.NotEqual(ShaderStage.None, translated.Stages);
            }
        }

        Assert.Equal(DescriptorKind.SampledTexture, effect.Bindings.Single(binding => binding.Name == "albedo").Kind);
        Assert.Equal(DescriptorKind.Sampler, effect.Bindings.Single(binding => binding.Name == "linear").Kind);
        Assert.Equal(DescriptorKind.StorageBuffer, effect.Bindings.Single(binding => binding.Name == "overflow").Kind);
    }

    /// <summary>
    ///     A struct array becomes a key per element.
    /// </summary>
    /// <remarks>
    ///     Raven describes <c>lights[].color</c> once, with an offset and a stride, because that is
    ///     what the shader declares. A parameter key holds one value, so leaving it collapsed makes
    ///     every element after the first unreachable by name — a light list whose second entry cannot
    ///     be set, and nothing anywhere says so.
    /// </remarks>
    [Fact]
    public void A_struct_array_becomes_a_key_per_element() {
        var effect = Lighting().TryGet(Key(shadows: false))!;

        var leaf = Reflection.GetProperty("Parameters")
            .EnumerateArray()
            .Single(parameter => parameter.GetProperty("Name").GetString() == "lights[].color");

        var origin = leaf.GetProperty("Offset").GetInt32();
        var stride = leaf.GetProperty("ArrayStride").GetInt32();

        for (var index = 0; index < 4; index++) {
            var element = effect.Parameters.Single(parameter => parameter.Name == $"Lighting.lights[{index}].color");

            Assert.Equal(origin + (index * stride), element.Offset);
            Assert.Equal(ShaderValueKind.Float3, element.Kind);
        }

        Assert.DoesNotContain(effect.Parameters, parameter => parameter.Name.Contains("[]", StringComparison.Ordinal));
    }

    /// <summary>The block's size comes across, because it is what a host allocates.</summary>
    [Fact]
    public void The_record_carries_the_block_size() {
        var effect = Lighting().TryGet(Key(shadows: false))!;

        var block = Reflection.GetProperty("Sets")
            .EnumerateArray()
            .SelectMany(set => set.GetProperty("Bindings").EnumerateArray())
            .First(binding => binding.GetProperty("Type").GetString() == "UniformBuffer");

        Assert.Equal(block.GetProperty("Size").GetInt32(), effect.ConstantBufferSize);
    }

    /// <summary>A key naming a shader this compilation does not have is a miss, not a failure.</summary>
    [Fact]
    public void An_unknown_shader_is_a_miss() => Assert.Null(Lighting().TryGet(EffectKey.Of("Nonexistent")));

    /// <summary>A shader that does not compile is something somebody has to read.</summary>
    [Fact]
    public void A_broken_shader_reports_what_is_wrong() {
        var path = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("n") + ".rvn");
        File.WriteAllText(path, "package Vixen.Fixtures\n\nshader Broken {\n    var x: float = nonsense\n}\n");

        // Either the parse or the binding refuses it; both are the compiler saying no, and both have
        // to reach the caller as something with the diagnostics in it.
        var error = Record.Exception(() => new RavenEffectCompiler([path]).TryGet(EffectKey.Of("Broken")));

        Assert.NotNull(error);
        Assert.True(error is ArgumentException or ShaderCompilationException);
    }

    // --- The closure --------------------------------------------------------

    /// <summary>
    ///     Three declared keys, two of which matter, is two variants.
    /// </summary>
    /// <remarks>
    ///     Doc 06's economy, measured. The cross product of what the fixture declares is eight
    ///     compilations for a shader that has two distinct outputs, and the difference is entirely
    ///     that Raven reports which keys a compilation read.
    /// </remarks>
    [Fact]
    public void Only_the_keys_that_matter_multiply_the_bundle() {
        var closure = PermutationClosure.Expand(Lighting(), "Lighting");

        Assert.Equal(2, closure.Effects.Length);
        Assert.Equal(["MaxLights", "UseShadows"], closure.Used);

        // Both keys are read whatever the other is, which is what makes a statically generated key
        // list able to name every variant this produces.
        Assert.False(closure.Dependent);

        Assert.DoesNotContain(
            closure.Effects,
            effect => effect.Permutations.Any(permutation => permutation.Name == "Lighting.Unused")
        );
    }

    /// <summary>A numeric key's interesting values are the project's to name.</summary>
    /// <remarks>
    ///     An <c>int</c> permutation cannot be enumerated — there are four billion of them — so
    ///     unless a caller says which matter it contributes its declared default alone. Which is
    ///     honest rather than clever: the bundle comes out missing the variants nobody asked for, and
    ///     a run reports them as misses by name.
    /// </remarks>
    [Fact]
    public void A_numeric_key_takes_the_values_it_is_given() {
        var closure = PermutationClosure.Expand(
            Lighting(),
            "Lighting",
            domains: new Dictionary<string, IReadOnlyList<string>> { ["MaxLights"] = ["4", "16"] }
        );

        Assert.Equal(4, closure.Effects.Length);

        Assert.Equal(
            ["16", "4"],
            closure.Effects
                .Select(effect => effect.Permutations.Single(permutation => permutation.Name == "Lighting.MaxLights").Value)
                .Distinct()
                .Order()
        );
    }

    /// <summary>
    ///     A key only read when another is on is found, which takes a second pass.
    /// </summary>
    /// <remarks>
    ///     The reason this is a fixed point and not a loop. <c>Nested</c> reads <c>Inner</c> only
    ///     inside <c>if (Outer)</c>, so the compilation with the declared defaults reports
    ///     <c>Outer</c> alone — and an enumeration that trusted that answer would bake two variants
    ///     and miss two. The set grows and the enumeration starts again; it is bounded by what the
    ///     shader declares, so it stops.
    /// </remarks>
    [Fact]
    public void A_key_hidden_behind_another_is_still_found() {
        var closure = PermutationClosure.Expand(Nested(), "Nested");

        Assert.Equal(["Inner", "Outer"], closure.Used);
        Assert.Equal(3, closure.Effects.Length);

        // And it says so, because a shader shaped like this is one whose extra variants a draw
        // cannot ask for: the engine picks the keys for its own key out of one checked-in
        // reflection, and that reflection came from a compilation that never reached `Inner`.
        Assert.True(closure.Dependent);

        // Outer off is one variant however Inner is set, because with Outer off nothing reads it.
        Assert.Equal(
            ["Nested[Nested.Inner=false,Nested.Outer=true]", "Nested[Nested.Inner=true,Nested.Outer=true]", "Nested[Nested.Outer=false]"],
            closure.Effects.Select(effect => effect.ToKey().ToString()).Order(StringComparer.Ordinal)
        );

        Assert.DoesNotContain(closure.Effects, effect => effect.ToKey().ToString().Contains("Never", StringComparison.Ordinal));
    }

    /// <summary>A shader with more variants than the limit fails the build rather than the afternoon.</summary>
    [Fact]
    public void An_explosive_shader_is_refused() =>
        Assert.Throws<InvalidOperationException>(() => PermutationClosure.Expand(Lighting(), "Lighting", limit: 1));

    // --- The bundle ---------------------------------------------------------

    /// <summary>What a build bakes is what a runtime resolves.</summary>
    [Fact]
    public void A_bundle_answers_the_keys_it_was_built_for() {
        var builder = new EffectBundleBuilder(Lighting());
        builder.AddClosure("Lighting");

        var bundle = Serializer.Read<EffectBundle>(Serializer.ToBytes(builder.Build()));
        var store = new EffectStore(bundle);

        Assert.Equal(2, store.Count);
        Assert.NotNull(store.TryGet(Key(shadows: true)));
        Assert.NotNull(store.TryGet(Key(shadows: false)));
        Assert.Empty(builder.Missing);
    }

    /// <summary>A manifest and a closure that overlap produce one entry, not two.</summary>
    [Fact]
    public void Reaching_one_variant_twice_bakes_it_once() {
        var builder = new EffectBundleBuilder(Lighting());

        builder.AddClosure("Lighting");
        builder.Add(EffectManifest.Of([Key(shadows: true)]));

        Assert.Equal(2, builder.Count);
    }

    /// <summary>A stale manifest is reported, not thrown, and all of it at once.</summary>
    [Fact]
    public void A_manifest_naming_a_shader_nobody_has_is_reported() {
        var builder = new EffectBundleBuilder(Lighting());

        builder.Add(EffectManifest.Of([EffectKey.Of("Deleted"), EffectKey.Of("AlsoDeleted"), Key(shadows: true)]));

        Assert.Equal(["AlsoDeleted", "Deleted"], builder.Missing.Select(key => key.ShaderName).Order(StringComparer.Ordinal));
        Assert.Equal(1, builder.Count);
    }

    /// <summary>The bundle is written where a content build picks it up.</summary>
    [Fact]
    public void A_bundle_is_written_and_read_back() {
        var path = Path.Combine(Path.GetTempPath(), "vixen-effects", Guid.NewGuid().ToString("n"), "Shaders.effects");

        var builder = new EffectBundleBuilder(Lighting());
        builder.AddClosure("Lighting");
        builder.Write(path);

        var store = new EffectStore(Serializer.Read<EffectBundle>(File.ReadAllBytes(path)));

        Assert.Equal(2, store.Count);
    }
}
