// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Vixen.Core.Syntax.Text;
using Vixen.Ui.Markup.Binding;

namespace Vixen.Ui.Markup.Emit;

/// <summary>
///     Turns a <see cref="BoundComponent" /> into the C# partial class that builds it.
/// </summary>
/// <remarks>
///     <para>
///         Per ADR-010 the output is imperative construction code, not a virtual DOM: one statement
///         per element, one effect per dynamic expression. Setting a signal invalidates exactly that
///         effect, which assigns exactly that property — no tree walk and no diff.
///     </para>
///     <para>
///         <b>Every fragment of C# that came from the <c>.vxml</c> is emitted under a
///         <c>#line</c> span directive.</b> That is the detail the whole approach rests on: it is
///         what lets the binder do no type resolution at all, because a misspelt component, an
///         unknown parameter and a wrong expression type are then reported by Roslyn against the
///         exact characters the author wrote — not against generated code they have never seen.
///     </para>
///     <para>
///         The directives use the span form (<c>#line (l,c)-(l,c) offset "file"</c>) rather than the
///         line form. The line form would land a squiggle at the start of a generated line, which
///         for <c>ctx.Bind(n3, "class", () =&gt; kind)</c> is several tokens away from the one word
///         that came out of the markup.
///     </para>
/// </remarks>
public sealed class ComponentEmitter {
    /// <summary>The namespace the generated code expects its runtime in.</summary>
    /// <remarks>
    ///     <c>Vixen.Ui.Composition</c>, in <c>Vixen.Ui</c> — which this assembly deliberately does
    ///     not reference. A markup compiler runs inside the C# compiler and cannot depend on the
    ///     framework it compiles for; it knows the contract by writing calls to it, and Roslyn
    ///     checks that it got them right. The tests do reference it, compile this output against it,
    ///     load the result and run it.
    /// </remarks>
    public const string RuntimeNamespace = "global::Vixen.Ui.Composition";

    readonly StringBuilder builder = new();
    readonly BoundComponent component;
    readonly string filePath;
    readonly string? @namespace;

    int depth;
    int names;

    ComponentEmitter(BoundComponent component, string filePath, string? @namespace) {
        this.component = component;
        this.filePath = filePath;
        this.@namespace = @namespace;
    }

    /// <summary>Emits a bound component as C#.</summary>
    /// <param name="component">What to emit.</param>
    /// <param name="filePath">The <c>.vxml</c> path <c>#line</c> directives point at.</param>
    /// <param name="namespace">
    ///     The namespace to declare the class in when the file does not name one, or null for the
    ///     global one.
    /// </param>
    /// <returns>The generated file's text.</returns>
    /// <remarks>
    ///     ⚠ <b>The file wins over the caller.</b> The caller that matters — the source generator —
    ///     offers the project's root namespace plus the file's own folders, which is the convention a
    ///     C# file in the same directory already follows and is right nearly always. It is not right
    ///     for a component whose folder is not what its namespace should be, and renaming the folder
    ///     is not a fix a library can rely on, so <c>@namespace</c> overrides it.
    /// </remarks>
    public static string Emit(BoundComponent component, string filePath, string? @namespace = null) {
        ArgumentNullException.ThrowIfNull(component);

        var emitter = new ComponentEmitter(component, filePath ?? string.Empty, component.Namespace ?? @namespace);
        emitter.EmitFile();
        return emitter.builder.ToString();
    }

    void EmitFile() {
        Line("// <auto-generated />");
        Line("#nullable enable");
        Line("#pragma warning disable CS1591");
        Line();

        foreach (var @using in component.Usings) {
            Line($"using {@using};");
        }

        if (component.Usings.Length > 0) {
            Line();
        }

        // File-scoped, so the class stays at depth zero: every `#line` span carries a generated
        // column computed from `depth`, and a braced namespace would shift all of them by four.
        if (!string.IsNullOrEmpty(@namespace)) {
            Line($"namespace {@namespace};");
            Line();
        }

        Line($"partial class {component.Name} : {RuntimeNamespace}.Component {{");
        depth++;

        EmitBuild();
        EmitTag();
        EmitStyle();
        EmitCode();

        depth--;
        Line("}");
    }

    void EmitBuild() {
        Line($"protected override void Build({RuntimeNamespace}.BuildContext ctx) {{");
        depth++;

        EmitNodes(component.Content, "ctx", "null");

        depth--;
        Line("}");
    }

    /// <summary>The <c>@tag</c> header, as the override of the property that answers it.</summary>
    void EmitTag() {
        if (component.Tag is not { } tag) {
            return;
        }

        Line();
        Line($"protected override string TagName => {Quote(tag)};");
    }

    void EmitStyle() {
        if (component.Css is not { } css) {
            return;
        }

        Line();
        Line($"protected override string? Style => {Quote(css)};");

        if (component.CssIsScoped) {
            Line("protected override bool StyleIsScoped => true;");
        }
    }

    /// <summary>
    ///     Copies every <c>@code</c> body into the class, verbatim, under its own <c>#line</c>.
    /// </summary>
    /// <remarks>
    ///     Verbatim is the point. A body is C# the author wrote and nothing here understands it, so
    ///     the only thing that can go wrong is the mapping — and the mapping is one directive.
    /// </remarks>
    void EmitCode() {
        foreach (var block in component.Code) {
            Line();
            Mapped(block, string.Empty, string.Empty);
        }
    }

    // ================================================================== Nodes

    void EmitNodes(ImmutableArray<BoundNode> nodes, string context, string parent) {
        foreach (var node in nodes) {
            EmitNode(node, context, parent);
        }
    }

    void EmitNode(BoundNode node, string context, string parent) {
        switch (node) {
            case BoundText text:
                Line($"{context}.Text({parent}, {Quote(text.Text)});");
                break;

            case BoundInterpolation interpolation:
                Mapped(interpolation.Expression, $"{context}.Text({parent}, () => ", ");");
                break;

            case BoundSlot slot:
                Line($"{context}.Slot({parent}, {Quote(slot.Name)});");
                break;

            case BoundElement element:
                EmitElement(element, context, parent);
                break;

            case BoundIf @if:
                EmitIf(@if, context, parent);
                break;

            case BoundSwitch @switch:
                EmitSwitch(@switch, context, parent);
                break;

            case BoundFor @for:
                EmitFor(@for, context, parent);
                break;

            default:
                break;
        }
    }

    void EmitElement(BoundElement element, string context, string parent) {
        var name = $"n{names++}";

        if (element.IsComponent) {
            // The tag name is a type name, so it is emitted as one, under its own span — which is
            // how an unknown component becomes "no such type" squiggled on the tag the author
            // wrote, with nothing here having had to resolve a type.
            Mapped(
                new(element.Tag, element.TagPosition),
                $"var {name} = {context}.Child<",
                $">({parent});"
            );
        } else {
            Line($"var {name} = {context}.Element({parent}, {Quote(element.Tag)});");
        }

        foreach (var attribute in element.Attributes) {
            EmitAttribute(attribute, element, context, name);
        }

        if (element.Children.IsEmpty) {
            return;
        }

        // ⚠ `Inner` and not the element itself, for both of the things a capitalised tag can name.
        // A component's children are content projected into it, so they hang from whatever element
        // it put its default slot on; a control's hang from its `ContentHost`, which is the control
        // for most of them and the interior part for a `ScrollView`, a `Popover` or an `Expander` —
        // an expander whose rows hung off the control would sit beside the part that collapsing
        // hides, and could not be shut. Which of the two overloads this is resolves at C# compile
        // time, the way `Target` does it.
        EmitNodes(
            element.Children,
            context,
            element.IsComponent ? $"{RuntimeNamespace}.BuildContext.Inner({name})" : name
        );
    }

    /// <summary>
    ///     The element an attribute applies to. For a component that is its root: <c>class</c> on
    ///     <c>&lt;Callout&gt;</c> styles the element the component drew, not the component object.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>A call rather than <c>.Root</c>, because a capitalised tag may name a control.</b>
    ///     <c>&lt;ProgressBar&gt;</c> and <c>&lt;Callout&gt;</c> are written identically and the
    ///     binder resolves no types, so which of them <c>n1</c> is cannot be known here — but
    ///     <c>Host</c> is overloaded on the two, and by the time the C# compiler reads it <c>n1</c>
    ///     has a type. The cost is a static call that inlines to nothing.
    /// </remarks>
    static string Target(BoundElement element, string name) =>
        element.IsComponent ? $"{RuntimeNamespace}.BuildContext.Host({name})" : name;

    /// <summary>
    ///     Attributes that mean the same thing on a component as on an element, and are therefore
    ///     never parameters.
    /// </summary>
    static bool IsUniversal(string name) => Binder.IsUniversal(name);

    void EmitAttribute(BoundAttribute attribute, BoundElement element, string context, string name) {
        switch (attribute.Kind) {
            case BoundAttributeKind.Key:
                // Consumed by the enclosing loop, which needs it before the element exists.
                break;

            case BoundAttributeKind.Event when attribute.Expression is { } handler: {
                var modifiers = string.Concat(attribute.Modifiers.Select(m => $", {Quote(m)}"));
                Mapped(handler, $"{context}.On({Target(element, name)}, {Quote(attribute.Name)}, ", $"{modifiers});");
                break;
            }

            case BoundAttributeKind.Bind when attribute.Expression is { } bound:
                // Two-way: a getter and a setter over the same expression. Roslyn rejects the
                // setter if the expression is not assignable, at the character that wrote it.
                Mapped(bound, $"{context}.TwoWay({Target(element, name)}, {Quote(attribute.Name)}, () => ", ",");
                Indented(() => Mapped(bound, "__v => ", " = __v);"));
                break;

            // `class` is universal. It names style classes, which a component's root element has
            // exactly as much as a `<div>` does — and it is a C# keyword, so treating it as a
            // parameter would emit `n1.class = …` and turn one bad attribute into a file that does
            // not parse.
            case BoundAttributeKind.Parameter when element.IsComponent && !IsUniversal(attribute.Name):
                EmitParameter(attribute, context, name);
                break;

            case BoundAttributeKind.Parameter when attribute.IsDynamic:
                Mapped2(
                    attribute.Value,
                    $"{context}.Bind({Target(element, name)}, {Quote(attribute.Name)}, () => ",
                    ");"
                );
                break;

            case BoundAttributeKind.Parameter:
                Line(
                    $"{context}.Attribute({Target(element, name)}, {Quote(attribute.Name)}, "
                    + $"{Quote(attribute.Literal ?? string.Empty)});"
                );
                break;

            default:
                break;
        }
    }

    /// <summary>
    ///     A parameter on a component instance, assigned by name so that the name is Roslyn's
    ///     problem rather than the binder's.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>A quoted value is not necessarily a string.</b> <c>Variant="Subtle"</c> assigns an
    ///     enum, <c>Value="0.5"</c> a float, and this side cannot tell which — so the literal goes
    ///     through <c>Literals.Of</c>, whose first argument is the property itself and exists to be
    ///     inferred from. The C# compiler then picks the conversion from the type of the thing being
    ///     assigned, and a property nothing converts to is an error on the attribute rather than a
    ///     surprise at run time.
    /// </remarks>
    void EmitParameter(BoundAttribute attribute, string context, string name) {
        var named = new BoundExpression(attribute.Name, attribute.NamePosition);

        if (!attribute.IsDynamic) {
            var literal = Quote(attribute.Literal ?? string.Empty);

            // ⚠ Two directives for one statement, because the property is named twice and a
            // parameter that does not exist is wrong at both. A single directive maps one fragment
            // and *extrapolates* everything after it, so the second mistake landed at a column
            // several words past the end of the line the author wrote.
            Mapped(named, $"{name}.", " =");
            Indented(() => Mapped(named, $"{RuntimeNamespace}.Literals.Of({name}.", $", {literal});"));

            return;
        }

        // Two directives, one statement: the first points at the parameter's name and the second
        // at the expression assigned to it. They are different mistakes and deserve different
        // squiggles, and a single directive can only aim at one of them.
        Mapped(named, $"{context}.Bind(() => {name}.", " =");
        Mapped2(attribute.Value, string.Empty, ");");
    }

    /// <summary>
    ///     An <c>@if</c> chain: one selector saying which arm is live, and one builder per arm.
    /// </summary>
    /// <remarks>
    ///     <c>@if</c> and <c>@switch</c> emit the same primitive. They differ only in how the arm
    ///     is chosen — a chain of conditions or a pattern match — and giving the runtime two
    ///     near-identical constructs to swap subtrees in and out would mean two places to get the
    ///     disposal of a branch's effects wrong.
    /// </remarks>
    void EmitIf(BoundIf @if, string context, string parent) {
        Line($"{context}.Switch({parent}, () =>");
        depth++;

        for (var i = 0; i < @if.Branches.Length; i++) {
            Mapped(@if.Branches[i].Condition, string.Empty, $" ? {i.ToString(CultureInfo.InvariantCulture)} :");
        }

        Line(@if.Else.IsEmpty ? "-1," : $"{@if.Branches.Length.ToString(CultureInfo.InvariantCulture)},");
        depth--;

        EmitArms([.. @if.Branches.Select(branch => branch.Body), .. @if.Else.IsEmpty ? [] : new[] { @if.Else }]);
    }

    void EmitSwitch(BoundSwitch @switch, string context, string parent) {
        Line($"{context}.Switch({parent}, () =>");
        depth++;
        Mapped(@switch.Subject, string.Empty, " switch {");
        depth++;

        for (var i = 0; i < @switch.Cases.Length; i++) {
            var arm = i.ToString(CultureInfo.InvariantCulture);

            if (@switch.Cases[i].Pattern is { } pattern) {
                Mapped(pattern, string.Empty, $" => {arm},");
            } else {
                Line($"_ => {arm},");
            }
        }

        // The catch-all goes in only when the markup did not write one. A `default:` arm already
        // emitted `_ =>`, and a second discard after it is unreachable — which C# reports, turning
        // a correct switch into a build error.
        if (!@switch.Cases.Any(section => section.Pattern is null)) {
            Line("_ => -1");
        } else {
            Trim();
        }
        depth--;
        Line("},");
        depth--;

        EmitArms([.. @switch.Cases.Select(section => section.Body)]);
    }

    void EmitArms(ImmutableArray<ImmutableArray<BoundNode>> arms) {
        var innerContext = $"c{depth.ToString(CultureInfo.InvariantCulture)}";
        var innerParent = $"p{depth.ToString(CultureInfo.InvariantCulture)}";

        depth++;
        Line($"({innerContext}, {innerParent}, __arm) => {{");
        depth++;
        Line("switch (__arm) {");
        depth++;

        for (var i = 0; i < arms.Length; i++) {
            Line($"case {i.ToString(CultureInfo.InvariantCulture)}: {{");
            depth++;
            EmitNodes(arms[i], innerContext, innerParent);
            Line("break;");
            depth--;
            Line("}");
        }

        Line("default: break;");
        depth--;
        Line("}");
        depth--;
        Line("});");
        depth--;
    }

    void EmitFor(BoundFor @for, string context, string parent) {
        Line($"{context}.For({parent}, () =>");
        depth++;
        Mapped(@for.Sequence, string.Empty, ",");

        if (@for.Key is { } key) {
            Mapped(key, $"{@for.Variable} => ", ",");
        } else {
            // No key: the item is its own identity. Not index-keyed — an index would make every
            // element after an insertion look changed, which is the failure the warning is about.
            Line($"static {@for.Variable} => {@for.Variable}!,");
        }

        var innerContext = $"c{depth.ToString(CultureInfo.InvariantCulture)}";
        var innerParent = $"p{depth.ToString(CultureInfo.InvariantCulture)}";

        Line($"({innerContext}, {innerParent}, {@for.Variable}) => {{");
        depth++;
        EmitNodes(@for.Body, innerContext, innerParent);
        depth--;
        Line("});");
        depth--;
    }

    // ================================================================== Writing

    /// <summary>
    ///     Writes one statement whose middle is a fragment of the <c>.vxml</c>, under a
    ///     <c>#line</c> that points at exactly that fragment.
    /// </summary>
    /// <remarks>
    ///     The offset in the directive is the number of generated characters before the fragment
    ///     starts, which is what makes the mapping land on the fragment rather than on the start of
    ///     the line — the whole reason for the span form.
    /// </remarks>
    void Mapped(BoundExpression expression, string prefix, string suffix) {
        var indent = new string(' ', depth * 4);
        Directive(expression.Position, indent.Length + prefix.Length);
        builder.Append(indent).Append(prefix).Append(expression.Text).Append(suffix).Append('\n');
        Line("#line default");
    }

    /// <summary>
    ///     The same, for a value made of several parts — <c>class="btn @kind"</c>, which is one
    ///     interpolated string with one mapped fragment per expression in it.
    /// </summary>
    void Mapped2(ImmutableArray<BoundValuePart> parts, string prefix, string suffix) {
        if (parts is [BoundExpressionPart single]) {
            Mapped(single.Expression, prefix, suffix);
            return;
        }

        Line($"{prefix}string.Concat(");
        depth++;

        for (var i = 0; i < parts.Length; i++) {
            var separator = i == parts.Length - 1 ? string.Empty : ",";

            switch (parts[i]) {
                case BoundLiteralPart literal:
                    Line($"{Quote(literal.Text)}{separator}");
                    break;
                case BoundExpressionPart part:
                    Mapped(part.Expression, string.Empty, separator);
                    break;
                default:
                    break;
            }
        }

        depth--;
        Line($"){suffix}");
    }

    void Directive(LinePositionSpan position, int offset) {
        var start = position.Start;
        var end = position.End;

        builder.Append("#line (")
            .Append(start.Line + 1)
            .Append(',')
            .Append(start.Character + 1)
            .Append(")-(")
            .Append(end.Line + 1)
            .Append(',')
            .Append(end.Character + 1)
            .Append(") ")
            .Append(offset)
            .Append(' ')
            .Append(Quote(filePath))
            .Append('\n');
    }

    /// <summary>Removes the trailing comma from the last written line.</summary>
    /// <remarks>
    ///     A switch expression's final arm takes no comma. Writing arms without one and adding it
    ///     before the next would mean every arm knowing whether it is last, across three different
    ///     emit paths; taking it off once here is the same result with one place to be wrong.
    /// </remarks>
    void Trim() {
        while (builder.Length > 0 && builder[^1] is '\n' or '\r') {
            builder.Length--;
        }

        if (builder.Length > 0 && builder[^1] == ',') {
            builder.Length--;
        }

        builder.Append('\n');
    }

    void Indented(Action write) {
        depth++;
        write();
        depth--;
    }

    void Line(string text = "") {
        if (text.Length > 0) {
            builder.Append(' ', depth * 4);
        }

        builder.Append(text).Append('\n');
    }

    static string Quote(string text) {
        var quoted = new StringBuilder(text.Length + 2).Append('"');

        foreach (var c in text) {
            _ = c switch {
                '"' => quoted.Append("\\\""),
                '\\' => quoted.Append("\\\\"),
                '\r' => quoted.Append("\\r"),
                '\n' => quoted.Append("\\n"),
                '\t' => quoted.Append("\\t"),
                _ => quoted.Append(c)
            };
        }

        return quoted.Append('"').ToString();
    }
}
