// SPDX-FileCopyrightText: Copyright (c) Rikarin
// SPDX-License-Identifier: Apache-2.0

using System.Text.Json;
using Vixen.Rendering.Features;
using Xunit;

namespace Tests;

/// <summary>
///     Where each of the forward pass's bindings lives, held against the shader's own reflection.
/// </summary>
/// <remarks>
///     <para>
///         The pass used to mark none of its bindings, which put every one of them in set 2 — the
///         material's — including the light list, the camera and the scene's environment. That is not
///         a tidiness complaint: <see cref="ForwardLightingRenderFeature" /> writes the per-object
///         block and binds it at set 3, so the shader and the feature that fills it disagreed about
///         which set it was in, and nothing anywhere said so. A shader that declares its sets is what
///         turns that from a thing a host remembers into a thing the build checks.
///     </para>
///     <para>
///         Asserted against <c>ForwardPlus.reflect.json</c> — Raven's own output, checked in beside
///         the shader and regenerated by a documented command — rather than against numbers typed
///         here, so this notices a change in the shader instead of merely surviving one.
///     </para>
/// </remarks>
public class ForwardPlusLayoutTests {
    static JsonElement Reflection => JsonDocument.Parse(File.ReadAllText(Path())).RootElement;

    /// <summary>The checked-in reflection, found by walking up rather than by counting directories.</summary>
    /// <remarks>
    ///     The same walk <see cref="MaterialReflectionTests" /> does, and for the same reason: how many
    ///     directories sit between a test assembly and the root is a build-configuration detail that
    ///     changes under <c>dotnet publish</c>.
    /// </remarks>
    static string Path() {
        for (var directory = new DirectoryInfo(AppContext.BaseDirectory); directory is not null; directory = directory.Parent) {
            var candidate = System.IO.Path.Combine(directory.FullName, "Raven", "Library", "Pipeline", "ForwardPlus.reflect.json");

            if (File.Exists(candidate)) {
                return candidate;
            }
        }

        throw new FileNotFoundException(
            "Raven/Library/Pipeline/ForwardPlus.reflect.json was not found above "
            + $"'{AppContext.BaseDirectory}'. Regenerate it with VIXEN_REGENERATE=1 in Vixen.Raven.Tests."
        );
    }

    static int SetOf(string binding) {
        foreach (var set in Reflection.GetProperty("Sets").EnumerateArray()) {
            foreach (var candidate in set.GetProperty("Bindings").EnumerateArray()) {
                if (candidate.GetProperty("Name").GetString() == binding) {
                    return set.GetProperty("Set").GetInt32();
                }
            }
        }

        return -1;
    }

    static (int Set, int Offset) ParameterOf(string name) {
        foreach (var parameter in Reflection.GetProperty("Parameters").EnumerateArray()) {
            if (parameter.GetProperty("Name").GetString() == name) {
                return (parameter.GetProperty("Set").GetInt32(), parameter.GetProperty("Offset").GetInt32());
            }
        }

        return (-1, -1);
    }

    /// <summary>Each binding is in the set whose lifetime it actually has.</summary>
    [Fact]
    public void Every_binding_is_in_the_set_its_lifetime_belongs_to() {
        // The scene: one sun, one environment, one shadow atlas, one set of probes, for the frame.
        Assert.Equal(0, SetOf("environment"));
        Assert.Equal(0, SetOf("shadowMap"));
        Assert.Equal(0, SetOf("probes"));
        Assert.Equal(0, SetOf("lightBuffer"));
        Assert.Equal(0, SetOf("clusters"));

        // The camera, in the block every shader in the frame shares.
        Assert.Equal(1, ParameterOf("viewProjection").Set);
        Assert.Equal(1, ParameterOf("viewPosition").Set);

        // The object's own.
        Assert.Equal(3, ParameterOf("lightCount").Set);
        Assert.Equal(3, ParameterOf("probeIndex").Set);
        Assert.Equal(3, ParameterOf("probeWeight").Set);
        Assert.Equal(3, ParameterOf("lights[].position").Set);
    }

    /// <summary>
    ///     The per-object block is laid out the way the feature that fills it writes.
    /// </summary>
    /// <remarks>
    ///     The disagreement this whole audit is about, reduced to four numbers. std140 starts an array
    ///     of structures on a sixteen-byte boundary, so the three scalars fill exactly the header the
    ///     feature already wrote — and the probe fields cost nothing, because that padding was there
    ///     either way.
    /// </remarks>
    [Fact]
    public void The_per_object_block_is_what_the_lighting_feature_writes() {
        Assert.Equal(0, ParameterOf("lightCount").Offset);
        Assert.Equal(ForwardLightingRenderFeature.ProbeIndexOffset, ParameterOf("probeIndex").Offset);
        Assert.Equal(ForwardLightingRenderFeature.ProbeWeightOffset, ParameterOf("probeWeight").Offset);
        Assert.Equal(ForwardLightingRenderFeature.HeaderSize, ParameterOf("lights[].position").Offset);
    }

    /// <summary>
    ///     The material's block holds the material's parameters and nothing else.
    /// </summary>
    /// <remarks>
    ///     The measure of what was wrong: set 2 was 1888 bytes because it carried a sixteen-entry light
    ///     list, a camera and a shadow transform. What a material set should hold is what the composed
    ///     surface declares, which for the default composition is a handful of floats.
    /// </remarks>
    [Fact]
    public void The_material_block_holds_only_the_material() {
        foreach (var parameter in Reflection.GetProperty("Parameters").EnumerateArray()) {
            if (parameter.GetProperty("Set").GetInt32() != 2) {
                continue;
            }

            var name = parameter.GetProperty("Name").GetString()!;

            Assert.DoesNotContain("light", name, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain("shadow", name, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain("probe", name, StringComparison.OrdinalIgnoreCase);
            Assert.DoesNotContain("view", name, StringComparison.OrdinalIgnoreCase);
        }
    }

    /// <summary>The world matrix is pushed, which is what the transform feature does with it.</summary>
    [Fact]
    public void The_world_matrix_is_a_push_constant() {
        var pushed = Reflection.GetProperty("PushConstants").EnumerateArray().Single();

        Assert.Equal(64, pushed.GetProperty("Size").GetInt32());
        Assert.Equal("world", pushed.GetProperty("Members").EnumerateArray().Single().GetProperty("Name").GetString());
    }

    /// <summary>The probe cubes are one binding with a count, which is what an index needs.</summary>
    [Fact]
    public void The_probes_are_one_binding_with_a_count() {
        var probes = Reflection.GetProperty("Sets")
            .EnumerateArray()
            .SelectMany(set => set.GetProperty("Bindings").EnumerateArray())
            .Single(binding => binding.GetProperty("Name").GetString() == "probes");

        Assert.Equal("SampledTexture", probes.GetProperty("Type").GetString());
        Assert.True(probes.GetProperty("Count").GetInt32() > 1);

        // And a volume per cube, in the same order, so one index reaches both.
        Assert.Equal(0, ParameterOf("probeVolumes[].box.minimum").Set);
    }
}
